;;; arxana-browse-test.el --- Tests for browsing helpers -*- lexical-binding: t; -*-

(require 'ert)
(require 'arxana-browser-browse)

(ert-deftest arxana-browse-open-catalog-defaults ()
  (let ((called nil))
    (cl-letf (((symbol-function 'article-menu-listing)
               (lambda (&rest _) (setq called t))))
      (arxana-browse-open-catalog nil)
      (should called))))

(ert-deftest arxana-browse-history-back-delegates ()
  (let ((called nil))
    (cl-letf (((symbol-function 'sb-back)
               (lambda () (setq called t))))
      (arxana-browse-history-back)
      (should called))))

(ert-deftest arxana-browse-parent-navigation ()
  (let* ((name-of-current-article "Child")
         (displayed nil)
         (article-called nil))
    (cl-letf (((symbol-function 'get-article)
               (lambda (name)
                 (setq article-called t)
                 (pcase name
                   ("Child" '(Child "body" (("Parent" parent))))
                   ("Parent" '(Parent (Intro Child Next)))
                   (_ nil))))
              ((symbol-function 'display-article)
               (lambda (target) (setq displayed target))))
      (should (equal name-of-current-article "Child"))
      (let ((ctx (arxana-browse--parent-context)))
        (should article-called)
        (should ctx)
        (should (equal (plist-get ctx :next) "Next"))
        (should (equal (plist-get ctx :prev) "Intro")))
      (arxana-browse-parent-next)
      (should (equal displayed "Next"))
      (setq displayed nil)
      (arxana-browse-open-parent)
      (should (equal displayed "Parent"))
      (setq displayed nil)
      (arxana-browse-parent-previous)
      (should (equal displayed "Intro")))))

(provide 'arxana-browse-test)
;;; arxana-browse-test.el ends here
