;;; arxana-scholium-test.el --- Tests for scholium authoring helpers -*- lexical-binding: t; -*-

(require 'ert)
(require 'cl-lib)
(require 'arxana-scholium)

(defvar new-scholium-name nil)
(defvar new-scholium-mode nil)

(ert-deftest arxana-scholium-compose-invokes-make-scholium ()
  (let ((new-scholium-name "Demo")
        (calls 0))
    (cl-letf (((symbol-function 'make-scholium)
               (lambda () (setq calls (1+ calls)))))
      (arxana-scholium-compose)
      (should (= calls 1)))))

(ert-deftest arxana-scholium-compose-region-delegates ()
  (let (captured)
    (cl-letf (((symbol-function 'make-scholium-about-part-of-current-article)
               (lambda (beg end) (setq captured (list beg end)))))
      (arxana-scholium-compose-from-region 10 20)
      (should (equal captured '(10 20))))))

(ert-deftest arxana-scholium-ensure-support-errors ()
  (should-error (arxana-scholium--ensure-support 'nonexistent-fn)
                :type 'user-error))

(ert-deftest arxana-scholium-authoring-mode-proxies ()
  (let ((calls '()))
    (cl-letf (((symbol-function 'new-scholium-mode)
               (lambda (arg) (push arg calls))))
      (arxana-scholium-authoring-mode 1)
      (arxana-scholium-authoring-mode 0)
      (should (equal calls '(-1 1))))))

(ert-deftest arxana-scholium-composes-about-target ()
  (let ((new-scholium-name "demo")
        (new-scholium-about nil)
        (calls nil))
    (cl-letf (((symbol-function 'make-scholium)
               (lambda () (push new-scholium-about calls))))
      (arxana-scholium--compose-about "Target")
      (should (equal calls '((("Target"))))))))

(ert-deftest arxana-scholium-redisplays-after-save ()
  (let ((new-scholium-about '(("Focus")))
        (shown nil))
    (cl-letf (((symbol-function 'display-article)
               (lambda (target) (setq shown target)))
              ((symbol-function 'escape-scholium-creation)
               (lambda (&rest _)
                 (setq new-scholium-about nil))))
      (arxana-scholium--escape-and-display #'escape-scholium-creation)
      (should (equal shown "Focus")))))

(ert-deftest arxana-scholium-create-resilient-adds-overlay ()
  (with-temp-buffer
    (insert "alpha beta gamma")
    (let ((arxana-scholium--overlays nil))
      (cl-letf (((symbol-function 'arxana-links-make-anchor)
                 (lambda (&rest _) '(:anchor demo)))
                ((symbol-function 'arxana-links-make-scholium)
                 (lambda (&rest _)
                   (list :status :anchored :content "Note")))
                ((symbol-function 'arxana-store-sync-enabled-p)
                 (lambda () nil))
                ((symbol-function 'arxana-links-persist-scholium)
                 (lambda (&rest _) nil)))
        (arxana-scholium-create-resilient 1 6 "Note")
        (should (= (length arxana-scholium--overlays) 1))
        (let ((ov (car arxana-scholium--overlays)))
          (should (eq (overlay-get ov 'face) 'arxana-scholium-anchored-face))
          (should (equal (overlay-get ov 'help-echo) "Note")))))))

(ert-deftest arxana-scholium-verify-updates-overlay-status ()
  (with-temp-buffer
    (insert "alpha beta gamma")
    (let ((arxana-scholium--overlays nil)
          (scholium (list :status :anchored :content "Note")))
      (arxana-scholium--add-overlay 1 6 scholium)
      (cl-letf (((symbol-function 'arxana-links-verify-scholium)
                 (lambda (&rest _) nil)))
        (arxana-scholium-verify-all)
        (let ((ov (car arxana-scholium--overlays)))
          (should (eq (overlay-get ov 'face) 'arxana-scholium-orphaned-face)))))))

(ert-deftest arxana-scholium-verify-keeps-fuzzy-face ()
  (with-temp-buffer
    (insert "alpha beta gamma")
    (let ((arxana-scholium--overlays nil)
          (scholium (list :status :fuzzy-matched :content "Note")))
      (arxana-scholium--add-overlay 1 6 scholium)
      (cl-letf (((symbol-function 'arxana-links-verify-scholium)
                 (lambda (&rest _) (cons 1 6))))
        (arxana-scholium-verify-all)
        (let ((ov (car arxana-scholium--overlays)))
          (should (eq (overlay-get ov 'face) 'arxana-scholium-fuzzy-face)))))))

(provide 'arxana-scholium-test)
;;; arxana-scholium-test.el ends here
