;;; arxana-browser-chorus-test.el --- Tests for chorus browser -*- lexical-binding: t; -*-

(setq load-prefer-newer t)

(require 'ert)
(require 'cl-lib)
(require 'arxana-browser-core)
(require 'arxana-browser-chorus)

(ert-deftest arxana-browser-songs-home-includes-chorus-catalog ()
  (cl-letf (((symbol-function 'arxana-browser-songs-menu-items)
             (lambda ()
               (list (list :type 'songs-catalog
                           :label "Suite songs"))))
            ((symbol-function 'arxana-browser-chorus-menu-items)
             (lambda ()
               (list (list :type 'chorus-catalog
                           :label "Demo choruses")))))
    (let ((items (arxana-browser--songs-items)))
      (should (equal '("Suite songs" "Demo choruses")
                     (mapcar (lambda (item) (plist-get item :label)) items))))))

(ert-deftest arxana-browser-chorus-menu-items-show-counts ()
  (let ((response
         '((:entities
            ((:entity/id . "chorus-2")
             (:entity/name . "Beta Chorus")
             (:entity/type . "arxana/chorus")
             (:entity/source . "beta"))
            ((:entity/id . "chorus-1")
             (:entity/name . "Alpha Chorus")
             (:entity/type . "arxana/chorus")
             (:entity/source . "alpha"))))))
    (cl-letf (((symbol-function 'arxana-store-sync-enabled-p) (lambda () t))
              ((symbol-function 'arxana-store-fetch-entities-latest)
               (lambda (&rest _) response)))
      (let* ((items (arxana-browser-chorus-menu-items))
             (demo (car items)))
        (should (eq (plist-get demo :type) 'chorus-catalog))
        (should (equal "Demo choruses" (plist-get demo :label)))
        (should (string-match-p "^2 entries\\." (plist-get demo :description)))))))

(ert-deftest arxana-browser-chorus-mode-maps-bind-left-return ()
  (should (eq #'arxana-browser-chorus-left-or-return
              (lookup-key arxana-browser-chorus-mode-map (kbd "<left>"))))
  (should (eq #'arxana-browser-chorus-left-or-return
              (lookup-key arxana-browser-chorus-notes-mode-map (kbd "<left>")))))

(ert-deftest arxana-browser-chorus-items-build-chorus-entities ()
  (let ((response
         '((:entities
            ((:entity/id . "chorus-2")
             (:entity/name . "Beta Chorus")
             (:entity/type . "arxana/chorus")
             (:entity/source . "beta line one\nbeta line two"))
            ((:entity/id . "chorus-1")
             (:entity/name . "Alpha Chorus")
             (:entity/type . "arxana/chorus")
             (:entity/source . "solo line"))))))
    (cl-letf (((symbol-function 'arxana-store-sync-enabled-p) (lambda () t))
              ((symbol-function 'arxana-store-fetch-entities-latest)
               (lambda (&rest _) response)))
      (let* ((items (arxana-browser-chorus-items '(:view choruses-demo)))
             (first (car items))
             (second (cadr items)))
        (should (= 2 (length items)))
        (should (eq (plist-get first :type) 'chorus-entity))
        (should (equal "Alpha Chorus" (plist-get first :label)))
        (should (= 1 (plist-get first :line-count)))
        (should (equal "Beta Chorus" (plist-get second :label)))
        (should (= 2 (plist-get second :line-count)))))))

(ert-deftest arxana-browser-chorus-open-renders-entity-text ()
  (let ((buffer-name "*Arxana Chorus*"))
    (unwind-protect
        (progn
          (cl-letf (((symbol-function 'arxana-store-fetch-entity)
                     (lambda (_id)
                       '((:entity . ((:entity/id . "chorus-1")
                                     (:entity/name . "Abi Chorus (demo)")
                                     (:entity/type . "arxana/chorus")
                                     (:entity/source . "the butterfly craves release to the open sky")))))))
            (arxana-browser-chorus-open '(:entity-id "chorus-1"))
            (with-current-buffer buffer-name
              (let ((content (buffer-substring-no-properties (point-min) (point-max))))
                (should (string-match-p "Title: Abi Chorus (demo)" content))
                (should (string-match-p "Type: arxana/chorus" content))
                (should (string-match-p "the butterfly craves release to the open sky" content))))))
      (when (get-buffer buffer-name)
        (kill-buffer buffer-name)))))

(ert-deftest arxana-browser-chorus-annotation-entries-retrieve-song-text ()
  (let ((chorus '((:entity/id . "chorus-1")
                  (:entity/name . "Abi Chorus (demo)")
                  (:entity/type . "arxana/chorus")
                  (:entity/source . "So go to the orange of purple or the blue of green, the blue of red")
                  (:props . ((chorus/source-song . "song:abi")
                             (chorus/source-songs . ("song:abi"))
                             (chorus/annotation-ids . ("hx:abi-blue"))))))
        (song '((:entity/id . "song:abi")
                (:entity/name . "Abi")
                (:entity/type . "arxana/song")
                (:entity/source . "Blue carnations, in the soil\nKiss me in the moonlight\nBlue daisies sleep\nKiss, my lips")))
        (hyperedge-response
         '((:hyperedge
            (:hx/id . "hx:abi-blue")
            (:hx/type . :annotation/supports)
            (:hx/props . ((:note . "Blue is treated as somewhere one can travel inside.")))
            (:hx/ends . (((:role . :annotated)
                          (:entity-id . "song:abi")
                          (:passage . "lines 1-4: Blue carnations, in the soil"))
                         ((:role . :source)
                          (:entity-id . "doc:blue")
                          (:passage . "So go to the orange of purple or the blue of green, the blue of red"))))))))
    (cl-letf (((symbol-function 'arxana-store-fetch-hyperedge)
               (lambda (_id) hyperedge-response))
              ((symbol-function 'arxana-store-fetch-entity)
               (lambda (id)
                 (pcase id
                   ("song:abi" `((:entity . ,song)))
                   (_ '((:entity . nil)))))))
      (let* ((entries (arxana-browser-chorus--annotation-entries chorus))
             (entry (car entries)))
        (should (= 1 (length entries)))
        (should (equal "Abi" (plist-get entry :song-name)))
        (should (equal "song:abi" (plist-get entry :song-id)))
        (should (string-match-p (regexp-quote "Blue carnations, in the soil\nKiss me in the moonlight\nBlue daisies sleep\nKiss, my lips")
                                (plist-get entry :song-text)))))))

(ert-deftest arxana-browser-chorus-annotation-entries-filter-by-source-song ()
  (let ((chorus '((:entity/id . "chorus-1")
                  (:entity/name . "Abi Chorus (demo)")
                  (:entity/type . "arxana/chorus")
                  (:entity/source . "So go to the orange of purple or the blue of green, the blue of red")
                  (:props . ((chorus/source-song . "song:abi")
                             (chorus/source-songs . ("song:abi"))
                             (chorus/annotation-ids . ("hx:abi-blue" "hx:old-man"))))))
        (song '((:entity/id . "song:abi")
                (:entity/name . "Abi")
                (:entity/type . "arxana/song")
                (:entity/source . "Blue carnations, in the soil\nKiss me in the moonlight\nBlue daisies sleep\nKiss, my lips"))))
    (cl-letf (((symbol-function 'arxana-store-fetch-hyperedge)
               (lambda (id)
                 (pcase id
                   ("hx:abi-blue"
                    '((:hyperedge
                       (:hx/id . "hx:abi-blue")
                       (:hx/type . :annotation/supports)
                       (:hx/ends . (((:role . :annotated)
                                     (:entity-id . "song:abi")
                                     (:passage . "lines 1-4: Blue carnations, in the soil"))
                                    ((:role . :source)
                                     (:entity-id . "doc:blue")
                                     (:passage . "So go to the orange of purple or the blue of green, the blue of red")))))))
                   ("hx:old-man"
                    '((:hyperedge
                       (:hx/id . "hx:old-man")
                       (:hx/type . :annotation/supports)
                       (:hx/ends . (((:role . :annotated)
                                     (:entity-id . "song:old-man")
                                     (:passage . "line 1: Some other song"))
                                    ((:role . :source)
                                     (:entity-id . "doc:blue")
                                     (:passage . "So go to the orange of purple or the blue of green, the blue of red")))))))
                   (_ '((:hyperedge . nil))))))
              ((symbol-function 'arxana-store-fetch-entity)
               (lambda (id)
                 (pcase id
                   ("song:abi" `((:entity . ,song)))
                   (_ '((:entity . nil)))))))
      (let ((entries (arxana-browser-chorus--annotation-entries chorus)))
        (should (= 1 (length entries)))
        (should (equal "song:abi" (plist-get (car entries) :song-id)))))))

(ert-deftest arxana-browser-chorus-open-renders-song-context-notes ()
  (let ((chorus '((:entity/id . "chorus-1")
                  (:entity/name . "Abi Chorus (demo)")
                  (:entity/type . "arxana/chorus")
                  (:entity/source . "So go to the orange of purple or the blue of green, the blue of red")
                  (:props . ((chorus/source-song . "song:abi")
                             (chorus/source-songs . ("song:abi"))
                             (chorus/annotation-ids . ("hx:abi-blue"))))))
        (song '((:entity/id . "song:abi")
                (:entity/name . "Abi")
                (:entity/type . "arxana/song")
                (:entity/source . "Blue carnations, in the soil\nKiss me in the moonlight\nBlue daisies sleep\nKiss, my lips")))
        (notes-buffer "*Arxana Chorus Notes*"))
    (unwind-protect
        (cl-letf (((symbol-function 'arxana-store-fetch-entity)
                   (lambda (id)
                     (pcase id
                       ("chorus-1" `((:entity . ,chorus)))
                       ("song:abi" `((:entity . ,song)))
                       (_ '((:entity . nil))))))
                  ((symbol-function 'arxana-store-fetch-hyperedge)
                   (lambda (_id)
                     '((:hyperedge
                        (:hx/id . "hx:abi-blue")
                        (:hx/type . :annotation/supports)
                        (:hx/props . ((:note . "Blue is treated as somewhere one can travel inside.")))
                        (:hx/ends . (((:role . :annotated)
                                      (:entity-id . "song:abi")
                                      (:passage . "lines 1-4: Blue carnations, in the soil"))
                                     ((:role . :source)
                                      (:entity-id . "doc:blue")
                                      (:passage . "So go to the orange of purple or the blue of green, the blue of red")))))))))
          (arxana-browser-chorus-open '(:entity-id "chorus-1"))
          (with-current-buffer notes-buffer
            (let ((content (buffer-substring-no-properties (point-min) (point-max))))
              (should (string-match-p (regexp-quote "Notes for Abi Chorus (demo)") content))
              (should (string-match-p "Blue carnations, in the soil" content))
              (should (string-match-p "Kiss me in the moonlight" content))
              (should (string-match-p "Blue is treated as somewhere one can travel inside\\." content)))))
      (when (get-buffer notes-buffer)
        (kill-buffer notes-buffer)))))

(ert-deftest arxana-browser-chorus-open-reuses-browser-window ()
  (let ((browser-buf (get-buffer-create "*Arxana Browser*"))
        (buffer-name "*Arxana Chorus*"))
    (unwind-protect
        (save-window-excursion
          (switch-to-buffer browser-buf)
          (split-window-right)
          (other-window 1)
          (switch-to-buffer (get-buffer-create "*scratch-chorus-side*"))
          (other-window -1)
          (cl-letf (((symbol-function 'arxana-store-fetch-entity)
                     (lambda (_id)
                       '((:entity . ((:entity/id . "chorus-1")
                                     (:entity/name . "Abi Chorus (demo)")
                                     (:entity/type . "arxana/chorus")
                                     (:entity/source . "the butterfly craves release to the open sky")))))))
            (arxana-browser-chorus-open '(:entity-id "chorus-1"))
            (should (equal buffer-name (buffer-name (window-buffer (selected-window)))))
            (should-not (get-buffer-window browser-buf t))
            (should (eq browser-buf
                        (with-current-buffer buffer-name arxana-ui-return-buffer)))))
      (when (get-buffer browser-buf)
        (kill-buffer browser-buf))
      (when (get-buffer buffer-name)
        (kill-buffer buffer-name))
      (when (get-buffer "*scratch-chorus-side*")
        (kill-buffer "*scratch-chorus-side*")))))

(ert-deftest arxana-browser-chorus-left-at-point-min-returns-to-browser ()
  (let ((browser-buf (get-buffer-create "*Arxana Browser*"))
        (buffer-name "*Arxana Chorus*")
        (notes-buffer "*Arxana Chorus Notes*"))
    (unwind-protect
        (save-window-excursion
          (switch-to-buffer browser-buf)
          (cl-letf (((symbol-function 'arxana-store-fetch-entity)
                     (lambda (_id)
                       '((:entity . ((:entity/id . "chorus-1")
                                     (:entity/name . "Abi Chorus (demo)")
                                     (:entity/type . "arxana/chorus")
                                     (:entity/source . "the butterfly craves release to the open sky"))))))
                    ((symbol-function 'display-buffer-in-side-window)
                     (lambda (&rest _) nil)))
            (arxana-browser-chorus-open '(:entity-id "chorus-1"))
            (with-current-buffer buffer-name
              (should (eq browser-buf arxana-ui-return-buffer))
              (should (window-configuration-p arxana-ui-return-window-config))
              (goto-char (point-min))
              (arxana-browser-chorus-left-or-return))
            (should (eq browser-buf (window-buffer (selected-window))))))
      (when (get-buffer browser-buf)
        (kill-buffer browser-buf))
      (when (get-buffer buffer-name)
        (kill-buffer buffer-name))
      (when (get-buffer notes-buffer)
        (kill-buffer notes-buffer)))))

(ert-deftest arxana-browser-chorus-demo-entity-specs-assemble-abi-material ()
  (let* ((spec (car (arxana-browser-chorus-demo-entity-specs)))
         (source (plist-get spec :source))
         (props (plist-get spec :props)))
    (should (equal arxana-browser-chorus-demo-id (plist-get spec :id)))
    (should (equal "Abi Chorus (demo)" (plist-get spec :name)))
    (should (equal "arxana/chorus" (plist-get spec :type)))
    (should (string-match-p
             (regexp-quote "So go to the orange of purple or the blue of green, the blue of red")
             source))
    (should (string-match-p
             (regexp-quote "the butterfly craves release to the open sky")
             source))
    (should (string-match-p
             (regexp-quote "a roving fluid without repurcussions, without any memory")
             source))
    (should (equal arxana-browser-chorus-demo-song-id
                   (alist-get 'chorus/source-song props)))
    (should (equal (list arxana-browser-chorus-demo-song-id)
                   (alist-get 'chorus/source-songs props)))
    (should (= 6 (length (alist-get 'chorus/annotation-ids props))))
    (should (= 2 (length (alist-get 'chorus/questions props))))))

;;; arxana-browser-chorus-test.el ends here
