* Prelude                                                          :noexport:
:PROPERTIES:
:LATEX_LABEL: prelude
:ID: prelude
:END:

** The philosophy
:PROPERTIES:
:LATEX_LABEL: the-philosophy
:ID: the-philosophy
:END:

The main concern here is to model systems for collaborative
authorship.  What freedoms and limitations are embodied in such
systems?  Working to understand how to empower users will hopefully
enable us to build a powerful and agile system; indeed, our goals here
extend beyond ``authorship'', to ``readership'' and query-answering;
that is, from hypertext to artificial intelligence.


** SBDM and CBPP

The idea of a \emph{scholia-based document model} (\emph{SBDM}) for
\emph{commons-based peer production} (\emph{CBPP}) is thematic for the
work.  Definitions for these terms suitable to the usage made within
this document are approximately as follows:
\begin{description}
\item[CBPP] the processes by which shared information resources
  are produced by multiple co-authors.
\item[SBDM] a framework for understanding the ways in which
  documents are put together out of smaller inter-referential
  components.
\end{description}


** Bits and pieces
:PROPERTIES:
:LATEX_LABEL: bits-and-pieces
:ID: bits-and-pieces
:END:

Scholia-based documents tend to be comprised of small pieces whose
semantic content has been illuminated through an ongoing process of
annotation.  This helps with refactoring, and with the process of
producing new, meaningful, derivative works.  Rich annotation also
opens the way to increasingly powerful computer-based inference about
the content of the document.  This document should be a good example.

\kw{testing}

\begin{figure}
\begin{center}
% \includegraphics[width=5in]{bw}
\end{center}
\caption{Author and summarizing example (\emph{apr\`es} L. Weiner). \label{author-as-scholium}}
\end{figure}

