* Experiments                                                      :noexport:
:PROPERTIES:
:LATEX_LABEL: experiments
:ID: experiments
:END:

** Experiments to try

This section should describe our experiments modeling different CBPP
systems that are out there in the world -- and coming up with new ones
that we like better.

In this section, we can describe some separate packages that provide
more interesting or advanced display features, for example.  Also
maybe some packages that do things with code (e.g. interactive
text-based games).  Wiki portage would be one basic thing to try.
Finally, of course, it would presumably be useful to get the HDM
codebase into the scholium system.

\begin{itemize}
\item Importing a wiki and getting the scholium system set up
to do wiki-like things.
\item Using the scholium system to write a play, novel, screenplay, or
  an interactive fiction type of game (actionable scholia would
  probably be part of just about any game).  Hipster the
  Gathering\footnote{http://planetx.cc.vt.edu/AsteroidMeta/Hipster\_the\_Gathering}
  would presumably be an easy game to code up.  My forays into ``fine
  literature'' with the Penmaster's Apprentice saga could also be
  typed up.  These things are currently interesting examples of
  physical scholia (see Section [[id:more-physical-scholia]]).
\item Using the scholium system to maintain a text-based forum
 or set of fora, as found on PM or slashdot.
\item Using the scholium system to manage an evolving codebase,
  e.g. HDM content, say APM and APM-$\Xi$, or this document itself
  (making the system interoperable with \LaTeX\ would be important).
\item Using the scholium system to manage TODO lists (like we used to
  do with TODL etc.).
\item Port GCIDE to Emacs and give instant access to definitions from
  within the browser.  Make GCIDE scholiumific (supplying semantically
  close definitions or whatever?).
\item do something like mmm-mode but using scholia about the buffer
  instead of begin/end regexps?
\item Make a semantic network describing relationships between words
  and use it for writing poetry.
\item make a system for exporting to other formats (see Note
  [[id:rendered-and-source-views]])
\item Write text-generation software that will provide different ways
  of viewing the network's structure.
\end{itemize}


** Cross-referencing in \LaTeX
:PROPERTIES:
:LATEX_LABEL: cross-refs-in-latex
:ID: cross-refs-in-latex
:END:

Note that the system of labels and references in \LaTeX\ allow you to
make ``hypertextual'' linear documents.  This system could perhaps be
extended (maybe by exploiting the scholium system).  It would be cool
to be able to cross-reference the relevant label in some other
document and have a suitable reference show up here.  This is a
scholium-like thing: how to make it work in \LaTeX?  (Maybe
\verb|\pmxref| should be able to refer to anything that has a
\verb|\label| about it.  Perhaps this would work already.)  This also
relates to the topic of Namespaces, see Section [[id:subcollections]].


** A comprehensive regression suite

This would be a fairly simple experiment, which would nevertheless
be very helpful for programming the system.  Namely, create 
a short program that tries to do everything that you can do with
the system.


** Go moves

It would be nice to have a browsable database of Go moves and games
with user annotations: presumably the already-existing Go resources
online include things like this.  If the scholium system can help
improve upon these resources, that would be cool.  For example,
perhaps gnugo's move book could be simultaneously an instruction
manual for human users.


** Games built of scholia

Note that the relationships of people to rooms (containment), people
to their backpacks (carrying), and so forth -- the basic elements of
text-based games -- are all interpretable as scholia-based.  The
``fantasy'' tie-in of these sorts of games works reasonably well with
the name Arxana.  If we're going to push development along this route,
it would be good to do some reading on MUD-like systems.


** Stress testing the system

It would probably be worth doing some empirical tests to see what
happens in a library full of a bunch of junk.  How long does it take
to find and display the one relevant scholium?  How much are things
helped by storing articles in namespaces?


** Scholia about functions

This function, or something like it, seems especially important if
we're going to use the scholium system to manage code.  Every time we
create a function, for example, it would be good to create a scholium
attached to that function (perhaps a scholium object whose \inp{name}
is the function's symbol name, though there could be the need to
disambiguate between the function and variable versions of the same
symbol) with a ``defined-in-buffer'' link \inp{about} the buffer in
which the given function definition is found; Emacs already has
functionality like this in its help subsystem.  This could be done by
explicit command or just on-the-fly by some appropriately-constructed
automatic function.

In addition, one could create scholia that say, for instance, which
functions that function calls.  Then, later, one could assemble a
who-calls or who-is-called listing about a given function, for the
user to browse.  Although this can be done easily enough already
(there is a who-calls.el), it is my sense that this approach would
save on search.  Browsing code at the ``who calls'' level seems
potentially interesting; it would be worth investigating the prior art
here more.


** Barkov's ``Hamlet''
:PROPERTIES:
:LATEX_LABEL: barkovs-hamlet
:ID: barkovs-hamlet
:END:

The system could be used to handily create different versions of a
play, e.g., to write a version of ``Hamlet'' manifesting the view that
actually Horatio is the
prince\footnote{http://www.geocities.com/shakesp\_marlowe/index.html} or to
splice in ``Rosencrantz and Guildenstern are Dead'' by Stoppard or
``King of Shreds and Patches'' by Elrord or whatever (assuming that
doing so was legally copacetic; for personal use of course it would
be).  Similarly, our treatment could describe theories about how the
play relates to things outside the play, or (being even more meta),
how the \emph{interpretation} of the play relates to the presentation,
or (still more), where the interpretation comes from, and how I think
\emph{my} interpretation of these various things gets involved.


** Using scholia on PlanetMath

Since articles in the encyclopedia are supposed to describe known
math, they aren't really the right place to describe new insights,
even if these new insights occur while reading that article.  (In
theory such insights could be discussed in the attached forum along
with basic questions or whatever; but a catch-all forum or collection
of catch-all fora and postings without metadata may not be the most
conducive to research-oriented work.)  My thought is, why not have an
attached discussion not in the encyclopedia for talking about some
particular advanced question.  This area can itself use encyclopedia
definitions as scholia to help orient casual readers.  This way,
treatments of established and ``live'' mathematics can develop
together.


** Implement a web browser that works with the scholium system
:PROPERTIES:
:LATEX_LABEL: nero2
:ID: nero2
:END:

Maybe I'll write this before long?  It seems like the sort of thing
that could be very helpful; search through scholia on web pages you've
browsed (and also download everything you browse and save it to
disk, so that you can search through the web pages themselves too).

Through this sort of approach, you might imagine the web (or portions
thereof) being  ``embedded'' in a more advanced hypertext system, at
least for some users.  Something similar can be done for working with
Project Gutenberg\footnote{http://www.promo.net/pg} or any
collection of computer-readable text.


** Use the scholium system to assist in literature review
:PROPERTIES:
:LATEX_LABEL: literature-review
:ID: literature-review
:END:

There are a number of different literatures that are relevant to the
scholium system.  From artificial intelligence, we have things like KM
or SNePS that are available as free software, and which can
accordingly be reviewed \emph{in their entirety}.  Or, at least in as
much of their entirety as seems useful.  It may be desirable to
simulate or at least partially simulate these systems (which is partly
what the \emph{preliminary} literature review is supposed to
determine, by looking at the basic theory of these systems).

In hypertext, there are systems like No\"osphere which can be treated
similarly.  Indeed, I am planning a meetup with No\"osphere's author,
Aaron Krowne, for purposes of mutual exchange over and potential
cross-breeding between these two systems.

There are no doubt many other interesting literature things to study
out there.  Deciding which ones will be most profitable to look at is
an interesting challenge.


** Backlink tricks
:PROPERTIES:
:LATEX_LABEL: backlink-tricks
:ID: backlink-tricks
:END:

One obvious thing to do with backlinks is to compute the
most-linked-to article, or, even better, to rank articles by their
popularity according to in-links.  This can be done by mapping a very
simple function over the \inp{metadata} label (or the ranking could be
maintained on the fly).

