** Use the scholium system to maintain a library of projects
:PROPERTIES:
:LATEX_LABEL: library
:ID: library
:END:

*** Managing several projects                                      :noexport:

We'll do several different experiments, some of which will involve
corpora that are (at least essentially) distinct.  One high-level
object to point at the ``main pages'' of these various projects might
come in handy.  There could be a number of other more advanced
library-like features to add later.


*** Managing workflow                                              :noexport:

In addition to simply presenting output of these projects, it would be
helpful to have the system set up to manage workflow (tasks and so
on).  For now, see [[id:appendix-cal]].


*** Library of major works

We have an overall structure for the digital library as a whole worked
out already (Section [[id:digital-library]]), but not yet a specific
list of major works.  It is convenient to have an index of these (just
like, later, it will be convenient to have many different indices of
different kinds of documents with different features).  So, we create
a virtual library to index these works in.  (Once this is set up
properly, of course the imported version of the scholium system itself
will be included.)

*However right now this isn’t working, so not exporting that code!*

#+BEGIN_SRC elisp :tangle no
(scholium 'major-articles nil nil 'label 'system)
#+END_SRC
