** On-the-fly scholium creation                                    :noexport:
:PROPERTIES:
:LATEX_LABEL: otf
:ID: otf
:END:

*** Why on-the-fly?

This section is about creating scholia automatically.  For example,
every time I type ``scholium system'', maybe something happens -- for
instance, maybe the text gets marked up with a reference to some other
object describing the scholium system.  This is sort of like what
happens in No\"osphere, though there, auto-linking happens when the
document is rendered.

Another similar thing is the auto-indexing feature present in Apple
Computer, Inc.'s latest OS, wherein content is automatically indexed
as it is being created.  We could do something fairly similar with the
scholium system (and some of this indexed information could be shared
with other collaborators whenever there are multiple people using the
scholium system together).

Another example use would be to display interesting feedback about
things you had just typed -- maybe related definitions or phrases,
or some other cool stuff.  Doing this on an automatic on the fly
basis is a minor simplification (from the user's point of view)
over doing it only when the user issues an explicit command.

Obviously you don't want to search every editspace.  For example,
displaying a \emph{definition} as a scholium means that you would
probably just want to search the dictionary namespace.  This is
\emph{not} the same as creating a scholium, indeed, the dictionary may
not ``really'' contain scholia at all; you can use the structure of
the dictionary to easily retrieve information that you would like to
superimpose on the current document.  (This is a somewhat traditional
sounding digital libraries sort of thing.)


*** Compare flyspell

Some good ideas might be available in the flyspell package for Emacs.


*** Automatically adding files to the article list

We can also set things up so that visited files are added to the
article list automatically, etc.


*** Lexical autolinking

One major application of this system would be to create
No\"osphere-like autolinking.  Thus, part of this ``experiment'' is to
reimplement autolinking in this model.  Note, that once you have
implemented linking within the model, then autolinking should probably
be ``easy'' to add by reimplementing the No\"osphere algorithm.  One
advantage of doing things this way is that links appear at edit time
rather than render time (presumably anyway), which means that they can
be tinkered with right away as needed.

I wonder if the autolinker could be used to make an index of terms
automatically, too?  Seems likely.

