** Model a physical space and its contents                         :noexport:
:PROPERTIES:
:LATEX_LABEL: space-model
:ID: space-model
:END:

*** Holtzermann Kitchen Companion

I've been thinking that it would be handy to have a full inventory
of the kitchen I share.  The inventory, or model, really, could be
shared with the kitchen-mates and it could help us remember where
things go and what needs to happen around the place.  More generally,
the idea would be: to help improve communication about goings on in
this shared space.


*** Typelock
:PROPERTIES:
:LATEX_LABEL: typelock
:ID: typelock
:END:

In order to talk about the contents of cupboards versus the
refrigerator, for example, the user should be able to specify
a bunch of `(contains A B)' relationships.  Both `contains'
and `A' will stay fixed for reasonably long periods of time.

In addition, probably everything that is created in this experiment
should have a \kw{kitchen-element} type (and label).  Thus,
we want some sort of typelock at the level of object creation
and link creation.  (Indeed, we could probably set things
up so that the links didn't need to be specially-typed, but
rather were just part of some specially-typed scholia.)

A sort of segue away from the main topic: it could be handy
to optionally display all of the `contains' items using the listing
mechanism instead of the standard scholia display.


*** Case for namespaces

% Let it not be said that this document contains everything but the
% kitchen sink.  Here is the sink.
Both the sink cabinet and the doorless cupboard contain a ``drawerful
of assorted utensils''.  Of course, these aren't \emph{the same}
drawers (nor are they the same utensils).  We find the same sort of
thing in earlier imports of the scholium system, in which several
sections had ``Further notes'' subsections.  As a work-around, all of
these were given distinct names, but subsequently, especially when
working with complexes of formulaic scholia (Note [[id:formulaic]]),
that behavior wouldn't be desirable.

