** Make more physical scholia                                      :noexport:
:PROPERTIES:
:LATEX_LABEL: more-physical-scholia
:ID: more-physical-scholia
:END:

*** Extended rendering

The scholium-based document idea can be extended outside of the
computer.  The examples that are produced this way can help illuminate
and inspire out work.  See Note [[id:physical-scholium-system]].


*** Math paper as gallery tour
:PROPERTIES:
:LATEX_LABEL: math-paper-as-gallery-tour
:ID: math-paper-as-gallery-tour
:END:

We could put pictures from a math paper on the walls of a gallery,
with the space divided up in such a way as to have each wing
correspond to a section of the paper.


*** Scholia on architectural space

A generalization of Note [[id:math-paper-as-gallery-tour]] is to put
together spaces that incorporate scholia into their surfaces
(graffiti, chalkboards), or into their basic design.  Memory spaces
(mnemonic architectures) are spaces with double (or more) meanings,
i.e., multiple sets of scholia on the same space.


*** The HPDA

This is a somewhat famous example (among a certain geek crowd) example
of a scholium-based document system.  I invented a game that goes
along with it.


*** Printing things out

Questions as to the impact and relevance of putting things on paper
continue.


*** Node-based systems

Systems like freemind\footnote{https://sourceforge.net/projects/freemind} aren't exactly
``physical'' in the sense of something you can handle, but they
provide a different sort of view into a document, and views are
physical things.  (It seems to that freemind itself only provides
hierarchical views, which isn't particularly pleasant for us.  I know
that the KM people had a tool that looked good for more complicated
views, but I'm also pretty sure they didn't want to release this tool
to the public.)  Some sort of nice graphical tool could be used to
make a schematic of the scholium system that people might find useful.


*** Outline management

In Table
# [[id:scheme-for-outline-managemnent]],
we illustrate
line-numbers 1--5 at left, items a--e at right, together with labels
$\alpha$--$\epsilon$.  We envision this outline changing over time,
and references such as \verb|\itemref{|$\alpha$\verb|}| consistently
producing the correct line number.  I think \LaTeX\ can already handle
this sort of thing, I just forget how you do it.
\begin{table}
\begin{center}
\begin{tabular}{ll}
1 & a ($\alpha$) \\
2 & \quad b ($\beta$) \\
3 & c ($\gamma$) \\
4 & \quad d ($\delta$) \\
5 & \quad \quad e ($\epsilon$) 
\end{tabular}
\end{center}
\caption{A scheme for outline management \label{scheme-for-outline-managemnent}}
\end{table}


*** Offline usefulness
:PROPERTIES:
:LATEX_LABEL: online-usefulness
:ID: online-usefulness
:END:

Printed documents are only useful offline; the question as to whether
they are more useful offline than a non-networked computer remains.
Sometimes they will have a certain pragmatic edge, e.g., they allow
one to avoid lugging the computer from place to place.  On the other
hand, one typically then must type up one's handwritten comments.

(The problem of integrating interesting documents into Arxana is
present whether or not these documents are physical.)


*** Getting jobs done in different ways

Many of the things we talk about in Arxana (and in the HDM project in
general) have to do with finding new ways to get jobs done which we
already can get done in some other way.  The hope is that the new ways
of working will allow us to be more efficient or have more fun or that
they will otherwise be beneficial.  (It isn't completely clear that
you really do get the same job done if you do it in a different way.)

