** Mathematics of the scholium system                              :noexport:
:PROPERTIES:
:LATEX_LABEL: mathematics
:ID: mathematics
:END:

*** Document topology

The conversation about identification of document regions has a very
topological flavor, as does the idea (also mentioned in the paper)
about stitching documents together out of articles attached along
their margins.


*** Cyberspace geometry

The ``observation'' mentioned in Note [[id:observation-on-cyberspace]]
could presumably be translated -- at least partially -- into a
statement about the hyperbolic geometry of cyberspace.  And I think
people have been studying this stuff for a while.  However, I think
there is more to the statement than just that.


*** Region arithmetic

The notion that regions can be copied, broken apart, deleted, and
added on the fly gives a notion of $*$, $/$, $-$, and $+$ for marked
up regions (and this applies to both text and markup).  I don't know
whether much can be made of these things, but they are the fundamental
operations, so perhaps there is something here.


*** Clusion algebra

Studying articles and clusions could be an interesting computational
variant on the study of objects and morphisms.


*** Transclusion linearity

The fact that transclusions shouldn't be indicated by constant, but
rather, linear, functions, seems cute (but I'm not sure what to make
of it).


*** Scholium mathematics in general

I'm particularly reminded of topology (including graph theory) and
ergodic theory.  ``Information theory'' seems related to the issues of
updates and versioning; similarly, ``knowledge theory'' may be related
to the issues of multi-directional updating.  From there we could move
on to game theory, I suppose, as the mathematical domain most
closely related to culture building (\emph{nomics}
are what I'm thinking of here; these also relate to MUDs).

Economics, more generally, seems to be where things are headed, when
we think about the social welfare situation associated with CBPP
system policies (e.g. rejecting corrections on PlanetMath has no
%% Maybe the open source version would be Franklinstein
repurcussions; if an essay about \emph{Frankenstein} is posted to the
site and the author rejects all corrections which say ``this is not
math!'', the administrators will presumably have to get involved, and
take some extra-protocol action to remove the article).

Other topics that should be taken up are the linguistic and
``mathematical artificial intelligence'' threads coming from the HDM
project.


*** Network navigation

If a scholium-based document is broken up into trees, the document's
underlying network can be linearized simply by ordering the roots of
these trees.  This relates to questions about literate programming and
proof checking (how do you write a ``structured proof''?).

