* Conclusions                                                      :noexport:
:PROPERTIES:
:LATEX_LABEL: conclusions
:ID: conclusions
:END:

** Original conclusion

In a context with multiple authors talking about many
intersubjectively important concepts, with ownership of the texts that
they write but freedom with the content, treating the total document
as a collection of scholia could provide important alternative
perspectives on a given subject.  The presence of on-screen scholia
could encourage responsible maintainership and aid users in making
specific comments and suggestions part of their critical reviews of
existing entries.


** Difficulty of putting things together

Technological difficulties are posed by the fact that a document must
be assembled out of several pieces for presentation purposes and the
fact that standard web browsers and editors may not be very useful for
browsing or creating these sorts of documents.  (This isn't
\emph{always} a difficulty; rather, it motivates the current
development effort!)  Compare the message on the outside of the
Walker (Figure
# [[id:author-as-scholium]]).

And: why didn't we see something like this document before?  Why
haven't the systems on the Hyperworlds server become ``popular''? I'm
not completely sure; there are probably a number of interrelated
reasons.


** Freedom in an online context

Another very important thing to talk about is free versus non-free web
services.  I'm not sure if we mean to completely \emph{skewer}
non-free systems, i.e., systems that don't have a collaborative free
scholia-based compenent to them.  But on the other hand, such systems
really may be much less useful.  The current model is basically: if
you want to create some commentary on something else, you need to find
your own platform/soapbox from which to make that commentary.  Some
systems, like PM's attached fora, invite commentary and provide a
place for it.  But many, many, pages out there do not invite
commentary or simply do not supply a place to put it.  Another thing
to notice about the scholia-based system is that it is very
egalitarian.  Just because something was ``there first'' doesn't make
it better.  The commentary can become just as important as the main
document, or more important.  On the other hand, it would be very
useful to develop some algorithms that can be used to sort out the
useful commentary from the utter crap.  Slashdot does a pretty good
job of this, but I think there is still room for improvement.  And,
even though PM provides attached fora, they could do a significantly
better job of exposing the content that is provided in those fora in
the ``default view'' or some ``secondary view'' of the object that is
being commented on.  It might just take something simple, like
expanding all of the threads, or possibly using some Slashdot-like
rating system to expand notable threads.  Both interactive and
automatic ways of determining the usefulness of certain feedback can
be used -- and there are already some things like this in Gnus (I'm
sure).


** Knowledge communities

It would also be good to talk about Ray's comments about knowledge
communities -- need to take another look at those again.  Also,
referring to other Ray stuff, I wonder what conditions would be
necessary for academics to accept more off-the-beaten-track
publications (e.g. PlanetMath).  Of course, if these things became
popular they wouldn't be off-the-beaten-track any more, really, but
let's not get circular.  My sense is that making some sort of medium
``respectable'' has to do with the social contract thing.  On the
other hand, people do seem to get respect for out-there stuff if it is
somehow novel, or useful, or \emph{something}.  (Not sure what the
relevant quality here is, how much ``uptake'' has to do with it, how
much ``propaganda'' (or ``PR'') or what -- if I knew maybe I'd try to
exploit this knowledge!)


** Social simplicity

Sometimes complexity may not be totally avoidable within the code.
(E.g. if there are 1 billion scholia about a given article, sorting
them would take a long time.)  Sometimes we can do clever things --
but other times we can probably rely on the user groups to structure
things in ways that won't push things too far.  It isn't clear how
much we can rely on them for this -- but my guess is that things that
the machine would whine about are frequently going things that people
want to avoid for their own reasons.


** Human and artificial intelligence
:PROPERTIES:
:LATEX_LABEL: human-and-artificial-intelligence
:ID: human-and-artificial-intelligence
:END:

The HDM project may be better off building something that smart people
can hack than building smart code right away.  Perhaps that's why I'm
giving precedence to the scholium system over things like parsers and
the like.  The ``human element'' in software development seems
powerful.  It is curious that I've envisioned the scholium system as
being mainly about the AI component of HDM; but it may be that we can
expect more from it, namely, a contribution to AI for HDM creation.
Take a look at Note [[id:text-and-code]] for some words against
thinking about things in terms of ``evolution towards actionable
form.''  I think a better argument would be for \emph{co-evolution}
(which is good, because there has been plenty of thinking done on this
issue).  SNePs seems to have some things to say on this
topic\footnote{http://www.cse.buffalo.edu/sneps/snerg.prospectus/node19.html}.
Presumably so do others; still, by contrast with many other systems,
the co-evolution view seems to be emphasized particularly strongly
here.


** Labels vs namespaces, transclusion vs inclusion, overlays vs text properties

It is interesting to compare the ``hard'' to the ``soft'' approaches,
both of which appear in this document in different roles (sometimes in
interestingly similar relationships to one another).


** Compatibility between versions of this system?

All else equal, it would be nice for any future versions of this
system to be compatible with this one.  But we can make no guarantees
that this will actually happen, although I do think that the system
will be revised somewhat to continue to make improvements and add new
features.


** Future work

It would be pleasant to have Arxana hooked up with a graphical
node/edge display, such as fenfire\footnote{http://fenfire.org}.
Building rich displays is a problem that we'll want to consider from
many angles (cf. Note [[id:large-form]]).  The usefulness of getting
various tools worked out in plain-text modes shouldn't be ignored!


** Getting work done on Arxana

We mentioned one strategic point, that of collaborating early on, in
Note [[id:collaborate-early]].  There are probably other things I
should be doing that would enhance my ability to get things done with
this system.  Productivity is a topic that should be studied more.
Working a lot, trying to check concrete usefulness or applicability a
lot, maintaining a strategic plan -- these all seem like good ideas.


\appendix
