* Appendix: Overview of specifications
:PROPERTIES:
:LATEX_LABEL: appendix-specs
:ID: appendix-specs
:END:

** A quick guide for the theoretically minded                      :noexport:

This section will contain an overview of the specifications of
\emph{this} scholium system, which, I think should help people who
want to hack on it, or who want to create \emph{other} scholium
systems.  The full theory is found in the main document, of course;
this section serves to remind the reader of points that are dealt with
in greater detail there.


** Spec for article

An article is an element of some namespace, by default,
the main article-table (a hash table).  
It takes the form of a quintuplet,
#+BEGIN_SRC elisp :tangle no
(name text about type bookkeeping)
#+END_SRC
where, when stored in the hash table, \inp{name} is used
as the key.  (See Note [[id:structure-of-articles]].)


** Spec for about data                                             :noexport:

About data in articles takes the form of a list of \emph{links}.  (See
Note [[id:format-of-about-field]].)


** Spec for link

Each link takes the form
#+BEGIN_SRC elisp :tangle no
(<target article's name> &rest <link-types>)
#+END_SRC
The design here maintains partial symmetry between the treatment of
article types and link types; the cdr of a link can be processed
by the same typedata processing functions as the \inp{type}
data from articles.  (See Note [[id:links]].)


** Spec for type data                                              :noexport:

A type can be a single token specifying a type or a list of types.
Types can, themselves, come with additional data; in which case they
take the form of a list, where the car gives the type's name, and the
cdr carries all additional specifics.


** Spec for metadata article

An article $A$ has metadata article $\tilde{A}$ whose
\inp{name} is 
#+BEGIN_SRC elisp :tangle no
(meta <name of A>)
#+END_SRC
The \inp{text} of a metadata article takes the form of a list of
lists, with each sub-list headed by a tag naming the contents of that
sub-list.  The \inp{about} data is `nil', the \inp{type} is `meta',
and the bookkeeping data is `system'.  (See Note
[[id:metadata-article-design]].)


** Spec for backlink

An article's backlinks are stored on the `backlink' field of its
metadata article.  An individual backlink
takes the form
#+BEGIN_SRC elisp :tangle no
(<name> <link number> [<version number>])
#+END_SRC
where ``name'' is the name of the article being backlinked, and
link number indicates the particular link to which this backlink
corresponds.  The optional version number is used if the backlink
corresponds to a specific version of the linking article other
than the most current one.
(See Note [[id:implementation-of-backlinks]].)


** Spec for link-id

The purpose of a link-id is to specify a link when marking up a piece
of text with a text property corresponding to a scholium, namely the
link through with that region was indicated (see Note
[[id:the-scholia-property]]; the `scholia' text property contains a
list of link-ids.).

The format of a link-id is
#+BEGIN_SRC elisp :tangle no
(<name> <link number>)
#+END_SRC

Notice that link-id's also come up in the context of masks and other
places.  They are a sort of idiom used in several places in the work
(as you can easily see by looking around at the specs shown in this
appendix).  One thing to notice is that the ``usable about data'' of
Note [[id:compute-usable-about-data]] \emph{et seq.} leads up to markup
fairly directly, and, in particular, that it computes markup by
applying masks to links as needed.  So, it is no wonder that there is
some continuity between these various parts of the system; and, in
particular, the fact that link-id's are a part of that continuity
makes sense.


** Spec for mask
:PROPERTIES:
:LATEX_LABEL: spec-for-mask
:ID: spec-for-mask
:END:

An article's masks are stored in the `masks' field of its metadata
article.  An individual mask takes the form
#+BEGIN_SRC elisp :tangle no
((<name> <link number>) &rest regions)
#+END_SRC
The regions are two-element lists, each giving the beginning and end
of a region that the link is being redirected to.  See Note
[[id:masking-links]] and Note [[id:masks]], and for further discussion
of the lack of generality in the current mask format, see Note
[[id:generality-of-masks]].


** Spec for `usable-about-data'

Something called ``usable-about-data'' is produced by the function
`compute-usable-about-data' (see Note
[[id:compute-usable-about-data]]).  This stuff is used when marking
things up (in particular, by `mark-up-scholium' and
`mark-up-reference').  The reason for documenting it here is that its
format is confusing and easy to forget.  I think that it would be best
if we could find another way to get this data to where it needs to be.

The format of the return value of `compute-usable-about-data'
is a list of elements of the form
#+BEGIN_SRC elisp :tangle no
((<name> <link number>) <beg end | nil>)
#+END_SRC
where name is the name of a scholium, `beg' and `end', if specified,
give the beginning and end of a marked region (yes, only one region
per link, as mentioned in Note [[id:links-indicating-passages]]),
whereas `nil' is specified if the link indicated by the `car' of this
form points at the whole of the article being rendered.  

(I am not a huge fan of this format, but it does seem to work;
however, maybe the name should be changed to ``usable about data for
markup'' or something like that, to make it clear why we are focusing
on data describing regions.)

(Also, perhaps we should note in this spec that instead of the
\inp{name}, sometimes ``(mask \inp{name})'' is used instead.  The
development here seems a bit confusing: if we use (mask \inp{name}),
is this a proper link-id?  Something to think about, I guess.)


** Comments on specs                                               :noexport:

I fear that the choice to allow a token or a list of types may come
back to bite later; it is certainly somewhat annoying now.  But I
think we're running with it?

Eventually we might want some specs for various operations or other
objects (e.g. transclusions are both operations and static objects).
But we can hold off on that til it is all defined.

Furthermore, we'll want to have clear specs for the formats that are
used \emph{in markup} (of regular links, links coming from references,
fake references, possibly etc.) but we don't quite have that taken
care of yet.

