* Appendix: Time and workflow management                           :noexport:
:PROPERTIES:
:LATEX_LABEL: appendix-cal
:ID: appendix-cal
:END:

** Framework for keeping track of time and events

People have been using calendars since the beginning of time
(literally!).  However, this is a case where reinventing the wheel
might be called for.  The scholium system can be used to keep track of
epochs of different scales, and maintain the proper relationships
between them.  Well, different calendar programs already exist that
will e.g. keep track of the events that are taking place in all of the
days of the month, and know (in some sense of the word) that these
events are taking place in that month.  But I think I can do somewhat
better for my needs.  One of the reasons is to keep a lot of data in
the system and integrate it up to get certain conclusions.
Furthermore, I want to keep track of the way big tasks get parceled
out to smaller time-scales.  Another useful feature is the ability to
go in the opposite direction, and produce somewhat realistic
predictions about what can be done by when.

So, we'll give it a shot.  

(Presumably if this ``appendix'' gets extremely verbose, big parts of
it should be chunked out into some other separate document.)


** Summer 2006

I want to get a releasable version of Arxana out.  I have to help
mentor Shaneal on his proof checking stuff.  I'd like to get started
with some NLP stuff.  I'd want to keep up with general reading and
correspondence related to the HDM project.  And finally, I want to do
some more math related things.


** Miscellaneous items that can get into release
:PROPERTIES:
:LATEX_LABEL: misc-items-for-release
:ID: misc-items-for-release
:END:

This stuff has come up as potentially important or at least
interesting to consider for the release.
\begin{itemize}
\item How about being able to spawn a semi-anonymous scholium rooted
  in the current article?
\item Build a subdocument library.
\item Make an easy to use demo.
\item Get a system for unique ID's working.
\item Import APM-Xi.
\item Go back over the internal formatting and display, and make sure
  that the format is actually used properly by the code that is
  supposed to use it.
\item Finish putting together the ``restricted view'' mode.
\item Perfect some system for managing clusions (including a
  simplified version for assembling a document from outlines).
\end{itemize}


** Revising the schedule

One of the most reasonable-seeming things to do when starting work is
to assess the schedule of events, and clarify exactly which activities
will be done during that work session.  Other clarifications to the
schedule can be effected at this point too.


** Release conditions

It would be nice to get some sort of system set up for collaborative
work on the same state-containing scholium system.  Maybe Arxana will
have to be made inherently peer-to-peer for this to work (given that
Emacs doesn't seem to include features for operating as a server with
several distinct users working on it at the same time).  Or
conceivably we can find a good back-end (e.g. in Common Lisp or
scheme?) to connect people to.  Another possibility that might work,
although it sounds like a little bit of a long-shot, is to get
Ebby\footnote{http://dev.technomancy.us/phil/browser/dotfiles/.emacs.d/ebby.el}
working with Gobby, or build on this system to make some
Emacs(-friendly) multi-user environment.  (Since Ebby apparently just
works as a client, I currently suspect that it won't directly solve
our state-maintaining problems.)

Since this all looks tricky, it seems to me that having some
acceptible (though certainly not perfected, that would be asking too
much) single-user environment ready to go even before making too many
more investigations of the multi-user stuff.  See Note
[[id:misc-items-for-release]] for the key details on this topic.


** Tue Jun  6 15:12:52 2006

I write this section up to the current point.  Then I think about what
to do next.  I guess it would be a good idea to look at importing
APM-Xi again, and maybe try to get the subdocument library stuff
working.  Since this should be fairly easy (at least initially).

