* Introduction                                                     :noexport:
:PROPERTIES:
:LATEX_LABEL: introduction
:ID: introduction
:END:

** A scholia-based document model for commons-based peer production
:PROPERTIES:
:LATEX_LABEL: sbdm4cbpp
:ID: sbdm4cbpp
:END:

The fundamental data structure used in this report is a simple
database made up of \emph{articles}, each of which has several
freeform components.  An article's \inp{name} is an arbitrary LISP
object, typically a string (two articles with the same name are
considered to be the same).  The articles can contain \inp{text} from
a string, buffer, or file (as well as from other sources).  An article
is supplied with \inp{about} and \inp{type} metadata which say,
respectively, what other pieces of the document the articles are
about, and generally how they are to be treated by the system.  A
collection of articles can be viewed as a semantic network, with links
from which \inp{about} data is constituted comprising the edges
between nodes (Note [[id:links]]).  (There are other sorts of links in
the system as well, cf. Note [[id:clusions]].)  Linking is how scholia
are attached to other articles; the collection of all articles is
``the commons''; and the rules for interacting with this collection
defines the commons's regulatory system.


** Inspirations
:PROPERTIES:
:LATEX_LABEL: inspirations
:ID: inspirations
:END:

One of the first things that got me thinking about this stuff was the
question of how to combine the contents of two digital libraries in a
useful and non-disruptive way\footnote{http://planetx.cc.vt.edu/AsteroidMeta/one\_week\_in\_october}.
From here, the more technical question of how to do bidirectional
updating between two digital libraries which share content and are
changing in real time arose (see Section [[id:bidi]]).  But probably
the most basic motivation comes from thinking about knowledge
representation and human interface for the Hyperreal Dictionary of
Mathematics project.  The aim of this project is to get the wolrd's
mathematical knowledge into a coherent machine-readable and
humanly-useful form.  I anticipate that the first major applications
of Arxana will be those directed towards building the HDM (see Section
[[id:HDM-things]]).

After thinking about these things for a while, I wrote up a few pages
that expressed some ideas I later learned to be the central notions in
Ted Nelson's Project Xanadu (see Note [[id:relationship-to-xanadu]]).
My interest in AI explains some of the differences between the two
designs; but the fact that I've chosen to use Emacs for development
probably explains even more.

Certainly the powerful text processing tools available in Emacs
(ranging from text properties and overlays to self-modifying code)
make it a great place to develop a next-generation hypertext system.
Existing Emacs-based hypertext systems, including the emacs-wiki
family of projects, and of course the built-in info and help
subsystems, give some sense of how useful Emacs-based hypertext can
be.

Much of the attitude towards AI developed here inherits from Minsky's
``Society of Mind''.  In addition, a certain amount of experience
working with contemporary AI systems (Cyc and KM) both got me to think
about what an AI system is and what I would like to see ``AI work''
become.

The style of writing is inspired by Knuth's ``\TeX: the program''.
Here, instead of a typesetting program that can be used to typeset a
description of itself, we have a hypertext system that can be used to
browse and edit a description of itself.  (Emacs had in fact pulled
that one off previously, and to great effect, but in a rather
different way.)

User freedom is probably the premier philosophical concern underlying
this endeavor.  My ideas about online freedom have something to do
with what I know about MUDs (which isn't a whole lot; mainly that they
are sometimes user-hackable and that they resemble the text-based
single-user games with which I am more familiar) and with my
experience as a participant in various CBPP environments.

Section [[id:philosophy]] delves further into these matters.


** Straightforward applications
:PROPERTIES:
:LATEX_LABEL: straightforward-applications
:ID: straightforward-applications
:END:

Although I am envisioning the system being used to work on projects of
grand scope and vision, it can also be used in some down-to-earth ways
that are relevant to many people: for instance, the system can be used
by document co-authors to annotate and comment on successive drafts of
an evolving paper.  Features to aid in this process have been present
in MS Word for some time, to the best of my knowledge.  (And in ASCII
you can do it with brackets [ins: like this :ins], OR WITH CAPS.)

(Getting things set up to make quick and easy side-comments on a
given text would be nice.)


** Acknowledgements
:PROPERTIES:
:LATEX_LABEL: acknowledgements
:ID: acknowledgements
:END:

Aaron Krowne both helped inspire the initial design (through a series
of discussions about PlanetMath, the HDM project, and bi-directional
updating between digital libraries) and helped to give it a coherent
initial expression\footnote{\label{corneli-krowne}Joseph A. Corneli
and Aaron P. Krowne, A scholia-based document model for commons-based
peer production. \emph{Proceedings of the Emory University Symposium
on Free Culture and the Digital Library}, 2005.}.

Ray Puzio helped to put the project on a sound theoretical and
philosophical foundation as it developed.

