** Overview of the system                                          :noexport:
:PROPERTIES:
:LATEX_LABEL: overview
:ID: overview
:END:

*** Scholia
:PROPERTIES:
:LATEX_LABEL: scholia
:ID: scholia
:END:

A ``scholium'' (plural ``scholia'') is a comment on something else.
We speak of a \emph{scholia-based document model} (or SBDM for short)
because speech is typically \emph{about} something.  We also refer to
elements of the larger document as ``articles''.  If an article isn't
\inp{about} anything (in the technical sense described in Note
[[id:definition-of-scholium]]) then then it is considered to be
degenerate as a scholium.  We will also talk about ``an article and
its attached scholia'' (regardless of whether or not the article is
itself a scholium attached to some other article).  Scholia need not
be pieces of text: they can also be code or markup telling the reader
(or the computer) how to process the article(s) they are written
about.


*** Generalized links
:PROPERTIES:
:LATEX_LABEL: generalized-links
:ID: generalized-links
:END:

The \inp{about} features described in Note [[id:scholia]] naturally
associate documents or parts of documents with one another.  This
generalizes the notion of \emph{link} familiar from the web (and other
places).  These familiar links are pieces of text with special markup
which say that are about some other piece of text:
#+BEGIN_EXAMPLE
<a href="document this link is about">text</a>
#+END_EXAMPLE
In the scholium system, links can overlap and can point at more
different kinds of targets than in typical hypertext systems.  Links
can also be given rich semantic properties by pairing them with
additional \inp{type} data and appropriately responsive procedures.

It is important to understand the fact that, in our system, markup and
metadata are typically stored as scholia linked to appropriate
targets.


*** Modeling the commons
:PROPERTIES:
:LATEX_LABEL: modeling-the-commons
:ID: modeling-the-commons
:END:

In addition to being capable of modeling many different kinds of
documents, the system developed here should be capable of modeling
and/or supporting the relevant features of the CBPP processes that
create these documents.  The SBDM is actually intended as a sort of
meta-model: a model for modeling models, including models of
documents, commonses, social contracts, culture building, and culture
change.  Cf.  Section [[id:experiments]] and Note [[id:the-system]].


*** Relationship to Xanadu
:PROPERTIES:
:LATEX_LABEL: relationship-to-xanadu
:ID: relationship-to-xanadu
:END:

The system presented here isn't meant to be an implementation of the
Xanadu idea, per se, although it provides some of the features one
would expect from a ``Xanadu implementation.''

I should probably mention that I haven't read all of Nelson's stuff
extra-closely, although I've looked through his books and enjoyed what
I saw there.  As the system here moves towards greater usability, I
assume I'll find the time to review the details from Nelson's writing
more closely and flesh out this comparison.  And I hope to have a
chance to review other systems that follow in the Xanadu lineage, e.g.
token_word\footnote{http://hypertext.sourceforge.net/token_word/} (which supposedly
implements ``almost every core feature of Xanadu'').  I guess it's the
hacker in me that makes me want to write the code first; and
certainly, the nature of the code I've produced thus far lends itself
to being helpful with literature review tasks
(cf. Note [[id:literature-review]]).  I'm pretty sure that this work
represents an advance, or at least steps in a new direction, for
Emacs-based hypertext.

One clear difference between this system and the Xanadu system is that
here articles are not supposed to be presented in a pay-to-access
fashion.  The idea of working on complicated systems for royalties or
license maintenance doesn't strike me as particularly compelling.
Also, in this system, articles can be deleted (see Note
[[id:deleting-articles]]), which as I understand it, is discouraged in
Xanadu (more investigation is warranted and the system for deletion
here needs finishing!).

To sum up, my overall sense is that Arxana, combined with simple
internet protocols could, very nicely, facilitate something
Xanadu-like, suitable for the current age.


*** When implementing something new

It is good to have an illustration of why the system is special and
different, and why it is also compatible with existing ways of
working.  This is true whether the system is based on code or mores
(e.g. why are principles of freedom important online?).  I'll be
devoting more time to making these illustrations in the future.  I
expect that such illustrations will do a lot to underscore the value
of the framework developed in this document (and, indeed, value is
often most obvious in the more concrete manifestations and examples of
a more general system).  Cf. Note [[id:principle-of-orthogonality]].


*** What doesn't work or needs debugging
:PROPERTIES:
:LATEX_LABEL: doesn't
:ID: doesn't
:END:

Here are some more details on things that we're planning to provide
at some point but haven't finished yet...

- We should support threaded followups and make other improvements to the display (see Note [[id:threading]]).
- ``Labels'' work but ``namespaces'' haven't been implemented yet (see Note [[id:labels-and-namespaces]]).
- We don't yet have support for ``actionable'' articles (see Note [[id:interactive-and-actionable-scholia]]).
- Various browsing features could be improved and extended (e.g. to enable deletion or editing of some subset of articles en masse), and probably debugged (especially the code from Section [[id:temporal]]).  The history mechanism could probably be debugged by displaying it.
- We haven't fully finished the code for deleting (Section [[id:deletion]]).
- Committing could stand to be beefed up with versioning (see Note [[id:we-adopt-a-versioned-model]]).
- We don't yet have support for saving articles selectively.  In particular, we hope to add support for saving only new or modified articles soon (but of course also for other predicates).  
- Support for derivative articles is somewhat lacking (Section [[id:derivative]]); in particular, I've done some work and sketching for transclusion and identification (Sections [[id:transclusion]] and [[id:identification]]) but I'm not yet happy with the results and have instead had to seek a temporary work-around.  These are some of the trickest technical problems tackled in this document (see Note [[id:difficulties-with-text-properties]]).  However, they should also be some of the ``killer aps'' when they are finished.
- Support for working in a distributed environment is lacking. I plan to add ``native'' support for CVS and/or GNU Arch soon\footnote{http://www.gnuarch.org/arch/how-arch-works.html}.
- Several of the experiments we describe haven't been attempted yet.
- Increased standardization and various other improvements should be effected throughout.
- We need to check and expand support for buffers and files within the scholium system; see [[id:principle-of-orthogonality]].  The question of scholia attached to the Scholia Display buffer may prove to be an especially annoying case; where will these be displayed? More generally and less confusingly, what should be done with scholia attached to buffers that have frequently-changing content? Perhaps these scholia can somehow be associated with those changes, and swapped in and out programmatically whenever the changes occur. We should debug the `display-scholia-about-current-buffer' function. See Note [[id:killed-buffers]] for an example of the sort of problem we have to deal with here.  (By keeping articles and buffers separate, we've made the first step towards insuring orthogonality, but we want to be sure of usefulness, too, e.g. by improving default loading of scholia for buffers.)
- We need to check how this loads against a plain-vanilla Emacs, and probably provide some easier means of getting started.
- Make it so that `sch-plain-text' (Note [[id:sch-plain-text]]) can display links.  In fact, we might want to always have it take in links, or the unlistified contents of links.  See Note [[id:datatypes]].
  - We should finish the functions for browsing parents; cf. Note [[id:forward-in-parent]].
  - Has the problem with committing a document that has a links at the start of its display been resolved?
- The system should be documented with use cases for all of its features; at least the basic ones.

Given that the basic system does work and hopefully provides an
exciting glimpse of what is possible here, now seems to be a
reasonable time to invite other people to help with some of these
issues.


*** Streamlined versions of this document

As mentioned in Note [[id:bits-and-pieces]], the system makes it easy
to produce certain kinds of derivative versions of a document.  Two
examples that may be helpful particularly helpful to readers are a
version that focuses on code (see Note [[id:with-code]]), and a version
that steers clear of code (see Note [[id:without-code]]).  Compare
``weave'' and ``tangle''.  (Of course, I do suggest reading everything
at some point; see Note [[id:motto]].)


*** A motto
:PROPERTIES:
:LATEX_LABEL: motto
:ID: motto
:END:

Certain issues cannot be resolved without writing code.

