** Consistency conditions                                          :noexport:
:PROPERTIES:
:LATEX_LABEL: consistency
:ID: consistency
:END:

*** Why we maintain consistency
:PROPERTIES:
:LATEX_LABEL: consistency-why
:ID: consistency-why
:END:

This discussion might go into Section [[id:philosophy]] or Section
[[id:mathematics]], but given that it is fairly foundational for the
system, it is worthwhile to at least include an overview early on.

When something changes in the system -- whether it is the addition of
an article, or the deletion of an article, or edits to an article --
very often the effects are not purely local; or at least, they
shouldn't be.  Someone may want to know when a certain kind of article
is created.  Articles that referred to an article that gets deleted
may want to refer to something else.  If an article changes,
references to specific regions of that article may have to be
re-directed or, in some cases, eliminated.

Many of these operations can be taken care of automatically by a
sufficiently powerful hypertext system.  Indeed, particularly in the
case of multi-user editing, the consistency conditions (considered as
a very general category) essentially constitute the \emph{social
  contract} associated with the work.


*** When we maintain consistency
:PROPERTIES:
:LATEX_LABEL: consistency-when
:ID: consistency-when
:END:

As we mentioned in Note [[id:consistency-why]], in the broadest sense,
we're always maintaining some sort of consistency.  But the three
major categories, \emph{adding}, \emph{deleting}, and \emph{editing},
give a nice first-run division of the cases.  (There may be some other
situations that will come up, and will not fit immediately into any of
these three groups, e.g. maintaining some state that isn't officially
part of an article per se, but at least ideally, we can decompose the
space this way.)

Sometimes users won't want certain ``weird'' things to happen to their
articles automatically.  For example, maybe someone really means to
point at the region between character position 5 and character
position 31 in some particular article, and not to the string that
currently appears in this region at the time when the link is created.
In this case, the person creating the link should say so -- and the
system should be set up to adhere to the reasonable wishes of its
users.  In particular, it should be entirely possible for two users to
have vastly different views of the document's contents!

(Notice that in the distributed case, it we may have to adopt somewhat
different notions of consistency; see Section [[id:distributed]].)


*** Consistency conditions for adding
:PROPERTIES:
:LATEX_LABEL: consistency-adding
:ID: consistency-adding
:END:

This is a fairly simple case, relatively speaking.
It includes such things as automatic labeling
# (cf. Section [[id:labels]])
as well as the automatic addition
of backlinks to appropriate articles (Note [[id:put-backlinks]]).


*** Consistency conditions for deleting
:PROPERTIES:
:LATEX_LABEL: consistency-deleting
:ID: consistency-deleting
:END:

The most important feature associated with deletion is to delete or
redirect backlinks.  See Section [[id:deletion]] for details.


*** Consistency conditions for editing
:PROPERTIES:
:LATEX_LABEL: consistency-editing
:ID: consistency-editing
:END:

This is by far the most complicated of the three cases.  When an
article is edited, links that point to its various components may have
to be updated.  In particular, when an article's \inp{about} data is
edited, anything that pointed at this data must change -- this
includes everything that uses link-id's (Note [[id:link-ids]]), i.e.,
backlinks in other articles, masks in the linking article, and markup.

Changes to an article's \inp{text} can have repercussions of similar
complexity, especially when derivative works are taken into account;
see Section [[id:derivative]] for details.

