** Further notes on scholia-based documents                        :noexport:

*** Following the design of metadata articles to make namespaces?
:PROPERTIES:
:LATEX_LABEL: metadata-design-for-namespaces
:ID: metadata-design-for-namespaces
:END:

Note that we could in theory follow a similar pattern with the meta
prefix to make additional ``namespaces'', i.e., the article ``(foo
\emph{bar})'' would be the article named ``bar'' within the namespace
``foo''.  We would maintain a label on these articles, as with the
``metadata'' label.  But it seems more desirable to create a namespace
\inp{type}, elements of which would have the property that they could
contain articles which aren't elements of the main article list.


*** Design of real namespaces

We currently only have one real ``namespace'' (see Note
[[id:metadata-design-for-namespaces]] for a way to create a fake
namespace).  A real namespace would probably have a list or a hash
table in the \inp{text} field and a ``namespace'' token into the
\inp{type} field.


*** Namespace narration

Presumably a lot of verbose discussion of namespaces can be trimmed
away when we actually have an implementation.


*** Finding namespaces by searching the namespace hierarchy

We should sometimes be able to find namespaces, by searching through
the namespace hierarchy for their name.  (I think I may have recently
seen an Emacs package posted to gnu.emacs.sources for doing something
similar with directories or files.)


*** Versioned backlinks?

Note that backlinks are outside of the editorial control of the person
whose article is being linked to.  Nonetheless, it may be handy to
maintain versioned backlink repositories, possibly to correspond to
different versions of linked-to and the linked-from articles (this
could be very complicated).


*** Holographic data
:PROPERTIES:
:LATEX_LABEL: holographic-data
:ID: holographic-data
:END:

There are a number of different strategies for working with
``holographic data'', i.e., data that represents a document but that
contains different bits and pieces all over, which must be assembled
to construct any particular view into the document.  Some of these
strategies involve maintenance of datastructures and some involve
search.  (See Note [[id:holographic-data-storage]] for some further
comments.)  For a pictoral illustration of something vaguely similar,
check out `animate-string'.


*** Simulating a unified catalog using many namespaces
:PROPERTIES:
:LATEX_LABEL: namespaces-vs-catalogs
:ID: namespaces-vs-catalogs
:END:

The argument for namespaces says that we could simulate a full catalog
by having functions that trace through all of the namespaces and
gather all of the articles that have been found there.


*** Are namespaces out-modded by labels?
:PROPERTIES:
:LATEX_LABEL: namespaces-outmodded
:ID: namespaces-outmodded
:END:

I'm not even sure if we should be using namespaces at all, but one
category of cases that seems to motivate their use that in which you
have objects that contain sub-objects.  Namespaces seem like a natural
model, even if we decide never to use them explicitly.


*** Remote subcollections

We might want to have one subcolection for each source of articles in
a distributed system.  For a built-in web browser, we might also want
to maintain directions for re-loading everything that's been
\emph{downloaded} from the internet, probably as its own subcollection
(with instructions on where to find the articles on disc and
remotely).


*** Holographic data storage
:PROPERTIES:
:LATEX_LABEL: holographic-data-storage
:ID: holographic-data-storage
:END:

This is the idea of a document in which data is stored ``all over'',
and our views into the document get different bits and pieces of this
data.  For example, in Table
# [[id:the-quick-brown-fox]],
the string
``the quick brown fox'' is stored in a somewhat non-intuitive way,
namely, indexed by letter of the alphabet rather than character
position.  If we look at a neighborhood of the letter ``o'' (in the
natural metric coming from this index), we might see something like
\begin{center}
????q???k??ro?n??o?
\end{center}
which gives us some idea of what the document as a whole has to say.
(As would any neighborhood of any element, hence the appellation
``holographic''.)

Similarly, an article displayed together with its scholia gives a view
into the document it is a part of.  In general, its scholia may come
from ``all over''.  We use backlinks (Note [[id:backlinks]]) to speed
the location of scholia necessary for presenting such views.

(Perhaps something from the theory of labels or something similar can
be used to speed things up too; e.g., I suppose that in addition to
generating this table, we could generate a list of the words in the
text too.  Something to think about I guess.)

\begin{table}
\begin{center}
\begin{tabular}{l|l}
{\bf character} & {\bf positions}  \\
\hline
 spc & 4, 10, 16\\
 b   & 11\\
 c   & 8\\
 e   & 3\\
 h  & 2\\
 i  & 7\\
 k  & 9\\
 n  & 15\\
 o  & 13, 18\\
 q  & 5\\
 r  & 12\\
 t  & 1\\
 u  & 6\\
 w  & 14\\
 x  & 19
\end{tabular}
\end{center}
\caption{\label{the-quick-brown-fox}Lexicographic storage for ``the quick brown fox''}
\end{table}


*** World-writable components versus metadata articles
:PROPERTIES:
:LATEX_LABEL: metadata-article-permissions
:ID: metadata-article-permissions
:END:

If we're going to maintain a collection of backlinks for each
linked-to article (which seems to be an exceptionally good idea), we
have to decide whether to maintain such a list as a part of the
article itself or as part of some other article (presumably an article
that contains nothing but metadata about the article that we're
working with).  This is an aesthetic consideration -- we're interested
in maintaining \emph{ownership} over articles, so for this reason, we
don't want them to contain world-editable components.  However, it may
not be so nice to have the article list filled up with system-owned
metadata articles, either.  Perhaps this is one case in which it would
be good to use a separate namespace.  (It is even conceivable that
users would want different behavior in different circumstances; e.g.
if all the articles are owned by one person, making portions of the
articles ``world-editable'' may not be such a problem.)


*** Savings afforded by backlinks

Here we assume that we use metadata articles of Note
[[id:metadata-article-permissions]] and that we use a hash table to store the
document. If we maintain a list of backlinks for each article, the
added look-up cost of adding a link is $O(1)$ per linked-to article
(i.e. we need to find the appropriate place to store the backlink
metadatum), and the cost to display an article is $O(1)$ per
linked-from article (i.e. we use the list of backlinks to find each
scholium attached to the article being displayed).  On the other hand,
if we don't maintain backlinks, there is no look-up cost associated
with adding a link, but there is a cost of $O(\#\mathrm{Articles})$
associated with document display, since we have to test every article
to see if it is \inp{about} the article being displayed.


*** Private information

This is one potential use of namespaces (we could have a public and a
private namespace... though actually this sounds a bit more like
something that we would want to use \emph{labels} for).  Privacy is
generally considered to be an important right.


*** Reading articles into a given namespace

If a bunch of scholia have been saved to a file, it would be
convenient to have a way to read them all into one specific namespace.


*** Intelligent search
:PROPERTIES:
:LATEX_LABEL: intelligent-search
:ID: intelligent-search
:END:

One topic we must concern ourselves with from time to time is the
\emph{scope of propagation}.  In a large system, we don't want to have
to look at everything after any given change.  Even if we maintain a
list of backlinks (see Note [[id:backlinks]]), we might well have to
search through everything in order to find the articles that are
backlinked to!  (Which may not be such a bad thing if we use a hash
table.)  Another possible solution is to try to search intelligently,
by using namespaces to guide the search.  If each backlink tells you
roughly where the corresponding linking article can be found, then you
can recover that article much more efficiently.  I'm pretty sure this
relates to the system for IP addressses used on the web and also to
the ``humber'' system used in Xanadu.  (The Wikipedia page about the
IP system probably contains important background).  See also Note
[[id:metadata-article-overview]] for related thoughts on using
namespaces to limit search.


*** Possible relationship between labels and `type' data

The \inp{type} field complements \emph{labels}; labels can be applied
by anyone, but type data can only be changed by the object's owner.
When you render an article, you look on its \inp{type} field first to
get the basic type data specified by the author.  Then you look at its
metadata article to find backlinks; if any of these backlinks are to
labels, you may find additional rendering information there.


*** Movable scholia
:PROPERTIES:
:LATEX_LABEL: movable-scholia
:ID: movable-scholia
:END:

At various places in the lifecycle of a scholium, we'll want it to
move around, either concretely (from one base of attachment to
another) or ephemerally (appearing in some new place while continuing
to be attached in its original location).  We already have various
features associated with some of these processes, for example,
transclusion (Section [[id:transclusion]]) is about viewing a given
article through some new window.  However, we'll want to do more,
e.g., one thing that should be coming soon is the ability to pass
scholia ``through'' a compilation (Section [[id:quick-compilations]]).
We'll eventually want to be able to do the reverse as well.  In
general, support for the various \emph{concrete} operations
(e.g. passing a scholium through a reference and making it stick) are
lacking at present.

