* Adding articles to the digital library                           :noexport:
:PROPERTIES:
:LATEX_LABEL: creation
:ID: creation
:END:

** Introduction to adding articles in the digital library

The code in this section provides various wrappers for the `scholium'
function, making it easy to create scholia.  Section [[id:bookkeeping]]
details the process of adding appropriate \inp{bookkeeping}
information to new articles; articles created using the functions in
this section have standard \inp{bookkeeping} information added to them
automatically.  Section [[id:adding-text]] concerns adding scholia
based on already-existing sources of text.  Section [[id:interactive]]
presents functions that the user would call to create articles in
which the \inp{text} field is filled in by the user.

For \emph{editing} articles that have already been added to the
library, see Section [[id:editing]].


** Setting `type' field at creation time

The user might want to set the \inp{type} field at creation time, not
just \inp{text} and \inp{about} (indeed, we could probably do a better
with \inp{about} in a few places, e.g. throughout Section
[[id:adding-text]]).  But if it is not provided immediately, \inp{type}
can still be edited in later.

