** Further notes on adding articles to the digital library         :noexport:

*** Forbid the creation of ``empty'' scholia?

Perhaps `make-scholium' should disallow (or at least display an idiot
box about) the creation of ``empty'' scholia -- they seem somewhat
silly.


*** Transcluded strings

We'd should have some function to insert an auto-updating string (like
the name for the buffer as an article).  We would typically want such
auto-updating portions to appear in a specially colored face.


*** Multi-reference creation?

This section should probably cover: the event of interactively making
a scholium that relates to several different pieces of text from
several different articles.  Note that you could probably do things
like this by using the generic list, and marking things in different
ways that show their relationship together, the create the new
scholium from that list.


*** Anonymous scholia

Creating ``anonymous'' scholia should probably be made possible; by
which I mean, the names of these scholia would be filled in
automatically but would be non-significant (compare `gensym').  Of
course, if we could have automatic names that were significant that
would be cool too.


*** Merging editorial comments

It would be nice if there was an easy way to merge editorial comments
into the main document, corresponding to the ability to make such
comments in the first place (Note [[id:straightforward-applications]]).

