** Database interaction
:PROPERTIES:
:LATEX_LABEL: interaction
:ID: interaction
:END:

*** The `article' function
:PROPERTIES:
:LATEX_LABEL: the-article-function
:ID: the-article-function
:END:

You can use this function to create an article with a
given name and contents.  You can optionally put it in a
list by specifying the heading that it is under.  (If this
is used multiple times with the same heading, that just becomes
a cone over the contents.)


#+BEGIN_SRC elisp
(defun article-2 (name contents &optional heading)
  (let ((coordinates (add-nema name
                               "has content"
                               contents)))
    (when heading (add-nema coordinates "in" heading))
    coordinates))
#+END_SRC

*** The `scholium' function
:PROPERTIES:
:LATEX_LABEL: the-scholium-function
:ID: the-scholium-function
:END:

You can use this function to link annotations to objects.
As with the `article' function, you can optionally
categorize the connection under a given heading (cf. Note
[[id:the-article-function]]).


#+BEGIN_SRC elisp
(defun scholium-2 (beginning link end &optional heading)
  (let ((coordinates (add-nema beginning
                               link
                               end)))
    (when heading (add-nema coordinates "in" heading))
    coordinates))
#+END_SRC

*** Uses of coordinates                                            :noexport:

It is convenient to do further immediate processing of the object
we've created while we still have ahold of the coordinates
returned by `add-nema' (e.g., for importing code
that is adjacent to the article, see Note
# [[id:import-code-continuations]]
).


*** On `get-article'
:PROPERTIES:
:LATEX_LABEL: get-article
:ID: get-article
:END:

Get the contents of the article named `name'.
We assume that there is only one such article for now.


#+BEGIN_SRC elisp
(defun get-article (name)
  (get-sink
   (first
    (nemas-given-beginning-and-middle
     (first
      (nemas-given-beginning-and-end
       name "arxana-merge.tex"))
     "has content"))))
#+END_SRC

*** On `get-names'
:PROPERTIES:
:LATEX_LABEL: get-names
:ID: get-names
:END:

This function simply gets the names of articles that have
names -- in other words, every triple built around the
``has content'' relation.\todo{This seems to work but
are both map operations needed?}


#+BEGIN_SRC elisp
(defun get-names (&optional heading)
  (mapcar #'get-source
   (mapcar #'get-source (nemas-given-middle "has content"))))
#+END_SRC
