** Managing windows and buffers
:PROPERTIES:
:LATEX_LABEL: managing-windows-and-buffers
:ID: managing-windows-and-buffers
:END:

*** Side-by-side buffers                                           :noexport:
:PROPERTIES:
:LATEX_LABEL: side-by-side-buffers
:ID: side-by-side-buffers
:END:

The first display style shows the main article in one buffer and
scholia about this article in another buffer.  The scholia may be
attached to specific regions of the main article, in which case, this
connection is shown graphically.  Other display styles
(e.g. threading, see Note [[id:threading]]) are in the works.


*** Special treatment of buffers and files                         :noexport:
:PROPERTIES:
:LATEX_LABEL: bias-towards-buffers
:ID: bias-towards-buffers
:END:

Buffers and files need some special treatment for display, even if
they don't need to be given much attention at scholium-creation time
(Note [[id:scholium-creation-modalities]]).  For example, it would be
nice to set up automatic display of scholia associated with a given
file if some spceial variable is set.  One class of buffers that
requires special treatment are the \emph{killed} ones (see Note
[[id:killed-buffers]]).  This issue relates to Note
[[id:the-emacs-way]].


*** Simpler side-by-side annotation                                :noexport:

A simpler method for doing side-by-side editing has been discussed
recently on the help-gnu-emacs mailing 
list\footnote{http://lists.gnu.org/archive/html/help-gnu-emacs/2005-07/msg00276.html}.
This gives local features similar to some of those provided by the scholium
system, but none of the global features.  (We should make sure that we
actually \emph{can} simulate this behavior, I think it should be no problem.)


*** A physical scholium system                                     :noexport:
:PROPERTIES:
:LATEX_LABEL: physical-scholium-system
:ID: physical-scholium-system
:END:

Working on this paper, I've taken to printing the document out
single-sided and binding the drafts along the margin, so that each
page has a blank facing page that I then use for notes.  Sounds
familar, doesn't it?  This approach is helping me understand how to
use paper better.  And it is giving me some ideas about useful
features to work into the electronic version.  See also Note
[[id:large-form]].


*** Working with large-form scholium systems                       :noexport:
:PROPERTIES:
:LATEX_LABEL: large-form
:ID: large-form
:END:

With larger pieces of paper, or other media, it is possible to put
together scholium-based documents with more content and more than two
columns.  With a couple of screens, or a larger screen, useful things
along these lines could be accomplished with Emacs too.  (As it is,
two side-by-side windows is about all that can be managed on my
computer.)

Working with large format documents, I noticed some interesting
effects.  On the left, I might see a document assembled out of several
smaller articles (say, by identification), and on the right, I would
see all of the comments that applied to any of these articles, while a
third columns would give comments that applied to text in the other
columns, or to the document as a whole, or to any of the other
articles that had gone into building previous columns.

Even with just a couple of columns to work with, various complex
things like this should be possible to do on the computer (e.g. with
different colors or different levels of indentation).

(The point is, eventually should be able to make more interesting sort
compilations than those described in Section
[[id:quick-compilations]].)


*** Avoiding information overload                                  :noexport:
:PROPERTIES:
:LATEX_LABEL: avoiding-information-overload
:ID: avoiding-information-overload
:END:

A tricky option would be to just display the scholia that relate
to portions of the document that are on the current screen.  The paper
version of Note [[id:physical-scholium-system]] does this by default.
But I'm not sure how to make Emacs behave this way.


*** Context                                                        :noexport:
:PROPERTIES:
:LATEX_LABEL: context
:ID: context
:END:

Context is important.  This is one of the reasons that scholia
themselves are important -- they get comments situated in a certain
\emph{con}text.  The notion of context seems to be different for
\emph{text} and \emph{hypertext}.  In text, everthing appears in
context, whereas in hypertext, nearby things sometimes don't appear at
all; they reside on the other side of a link, and may never be seen by
a reader.  But this duality is somewhat misleading, in particular, it
is sometimes thecase that ``information overload'' would occur if
everything appeared on the same page or in the same place.  And
sometimes the context of the page can be misleading; regular text
frequently relies on global contextual features. (And of course,
readers might not actually see everything that is on the page!)  It is
an interesting feature of reality and human psychology that contexts
are often decipherable -- we can figure out how things fit together.
A ``good'' hypertext model should presumably include features that
reflect this aspect of our thinking, and allow users to explicitly
recontextualize things as they see fit.  For some technical
suggestions on this matter, see Note [[id:displaying-nearby-scholia]].


*** Dot dot dot

How should scholia in later generations be displayed?  In the default
mode, without threading, a ``dot dot dot'' would be useful.  (And in
the case of scholia that bridge the gap between two articles, the
``dot dot dot'' probably needs to have a special meaning.)  Anyway,
note that these dot-dot-dotted things could be found by a depth-first
search through the document collection.  (Find anything \inp{about}
the current article, then find anything \inp{about} that, etc., then
find the next thing \inp{about} the current article, 
etc.)\footnote{Compare the 2nd figure in Corneli and Krowne (2005)
(cf. Footnote
# [[id:corneli-krowne]],
Page \pageref{corneli-krowne}).}.
% How to get page reference corresponding to a label?


#+BEGIN_SRC elisp
(defvar pre-sch-win-config nil "Saved window configuration.")
(defvar sch-win-config nil "Saved window configuration.")

(defvar buffer-associated-with-current-article nil)
#+END_SRC

*** On `article-buffered'

Here's a little convenience function that tells you whether the
article's text lives in a buffer or not.


#+BEGIN_SRC elisp
(defun article-buffered (article)
  (bufferp (scholium-text article)))
#+END_SRC

*** Make new buffered article                                      :noexport:

We should provide some command to make a new article in a new
buffer, all in one shot.


*** Detaching articles from buffers                                :noexport:

Perhaps it should be possible to detach a buffered article from the
buffer that contains it.


*** On `scholia-overwhelm-display'
:PROPERTIES:
:LATEX_LABEL: scholia-overwhelm-display
:ID: scholia-overwhelm-display
:END:

This function displays scholium stuff.  It is called by
`display-article' (Note [[id:display-article]]) and
`display-scholia-about-current-buffer'
(Note [[id:display-scholia-about-current-buffer]]).  If
there is a main article buffer (i.e. the article to be displayed lives
in its own buffer), we use that buffer to display the article;
otherwise, we use the ``Main Article Display'' buffer.  Scholia that
match the appropriate set of conditions in `mark-things-up' will be
rendered to the ``Scholia Display'' buffer.


#+BEGIN_SRC elisp
(defun scholia-overwhelm-display (text)
  (unless pre-sch-win-config
    (setq pre-sch-win-config (current-window-configuration)))
  (delete-other-windows)
  (split-window-horizontally)
  (if rendering-target-buffer
      (pop-to-buffer rendering-target-buffer t)
    (switch-to-buffer (get-buffer-create "Main Article Display") t))
  (erase-buffer)
  (insert text)
  (goto-char (point-min))
  (setq buffer-associated-with-current-article (current-buffer))
  (other-window 1)
  (switch-to-buffer (get-buffer-create "Scholia Display") t)
  (erase-buffer))
#+END_SRC

*** Switching between views
:PROPERTIES:
:LATEX_LABEL: switching-between-views
:ID: switching-between-views
:END:

We offer a few convenient functions for switching between the
article-plus-scholia browsing display and whatever came before.  It
would also be nice to offer a function for switching between the
article display and the generic listing display.


#+BEGIN_SRC elisp
(defun back-to-normal ()
  (interactive)
  (setq sch-win-config (current-window-configuration))
  (set-window-configuration pre-sch-win-config)
  (setq pre-sch-win-config nil))

(defun back-to-other-view ()
  (interactive)
  (setq pre-sch-win-config (current-window-configuration))
  (set-window-configuration sch-win-config)
  (setq sch-win-config nil))
#+END_SRC
