** Deletion
:PROPERTIES:
:LATEX_LABEL: deletion
:ID: deletion
:END:

*** Deleting articles                                              :noexport:
:PROPERTIES:
:LATEX_LABEL: deleting-articles
:ID: deleting-articles
:END:

It is sometimes desirable to delete articles that are no longer worth
looking at.  We want to give the user this power, though in some cases
it would be nice if the article wasn't really deleted and was instead
just \emph{depreciated}.

There is a somewhat complex operation that should be executed when an
article is actual deleted (and/or, conversely, a somewhat complex
system we should put in place to deal, at render time, with articles
that have been deleted without sufficient follow-through).  Some of
the steps in the deletion process should be: (1) deleting backlinks;
(2) unindexing the article from whatever labels the article has been
indexed in.

But right now, we just delete.


*** Steps to be taken when deleting an article                     :noexport:
:PROPERTIES:
:LATEX_LABEL: steps-when-deleting
:ID: steps-when-deleting
:END:

If the article is a scholium attached to the current article,
we should remove the associated text properties and overlays.

Since in theory we can't modify the \inp{about} data that point
at the deleted article, we might want to broadcast a signal to
these articles that say that their referent has been deleted.
One way to do this would be to replace the article with a
``Deleted Article'' stub, and probably add it to a ``deleted''
label.

Of course, as with other issues having to do with \emph{propagation}
things are somewhat different if all the articles are owned
by the same person (or otherwise have conventions associated
with them whereby they can be kept in sync without problems).


*** Set current article to `nil'

If the current article is deleted, then the `name-of-current-article'
variable should probably be set to nil.  (Either that, or something
from the temporal browser should be used to set the variable to the
last-browsed page.)


#+BEGIN_SRC elisp
(defvar delete-article-hook nil)

(defun delete-article (name)
  (interactive (list (read-article-name)))
  (let ((article (get-article name)))
    (if article
        (progn
          (remhash name article-table)
          (when (equal name name-of-current-article)
            (setq name-of-current-article nil))
          (run-hooks 'delete-article-hook))
      (error "No article by that name found"))))
#+END_SRC

*** Deal with effects on temporal browser                          :noexport:

It is a little weird to revised history to make it look like deleted
pages \emph{never existed}.  Seriously Orwellian.  For now, that's
exactly what we do.


*** On `remove-appearances-in-history'

This function will run inside the scope of `delete-article'.


#+BEGIN_SRC elisp
(defun remove-appearances-in-history ()
  (setq sb-history (delete name sb-history)))

(add-hook 'delete-article-hook 'remove-appearances-in-history)
#+END_SRC

*** Deal with effects on articles that deleted article was attached to :noexport:

Presumably articles that the deleted article linked to will have to
have their backlinks adjusted.  That is to say, it would be somewhat
odd to have backlinks to an article that doesn't exist.


*** On `delete-scholium-associated-with-current-marked-region'

Provides a quick way to delete the scholium attached to region
containing point.  If more than one scholium is so attached,
we bring up a menu to select items for deletion.

This function assumes that the `scholia' property is simply
comprised of a list of the names of attached scholia; I'm
not so sure that this is an accurate assumption (if not,
then we should be able to easily extract such a list from
the actual `scholia' property).

This is just one of several functions that would benefit from
the addition of progressive markup modifications.


#+BEGIN_SRC elisp
(defun delete-scholium-associated-with-current-marked-region ()
  (interactive)
  (let ((linked-scholia (scholia-named-at-point)))
    (cond
     ((eq (length linked-scholia) 0)
      (message "No scholium attached here."))
     ((eq (length linked-scholia) 1)
      (delete-article (car linked-scholia)))
     (t
      (list-articles linked-scholia)
      (message
       "Inspect articles and select items for deletion with \"d\".")))))
#+END_SRC

*** Deletion in various strengths                                  :noexport:

Probably there should be several different kinds of
deletion (like in X windows, there is kill, destroy, minimize, wipe
out to the fifth generation, etc.; also, compare the several
different ``strengths'' derivative articles come in).

