** Introduction to clusions
:PROPERTIES:
:LATEX_LABEL: intro-to-derivatives
:ID: intro-to-derivatives
:END:

*** Derivative works in the scholium system                        :noexport:
:PROPERTIES:
:LATEX_LABEL: derivative-works-in-the-scholium-system
:ID: derivative-works-in-the-scholium-system
:END:

Section [[id:rendering]] focuses on providing useful views \emph{into}
the document.  The matter of assembling \emph{new articles} which
derive from other articles drawn from the document is essentially a
separate problem; we will tackle this problem in this section.  (Other
sorts of derivative or derivative-like works, such as collections and
indices are given their primary treatment elsewhere.)


*** Different kinds of derivatives                                 :noexport:
:PROPERTIES:
:LATEX_LABEL: different-kinds-of-derivatives
:ID: different-kinds-of-derivatives
:END:

\emph{Inclusion} is probably the most straightforward way to assemble
an an article that derives from another article.  Material from a
certain version of the source article is simply inserted into the
current article.  Inclusion is treated in Section [[id:inclusion]].
\emph{Transclusion} is similar to inclusion, except that instead of
simply inserting source text as it is right now, transclusion causes
the source to be tracked as it changes, and its most up-to-date
version to appear automatically in the derivative work when it's
rendered.  Transclusion is treated in Section [[id:transclusion]].
\emph{Identification} is like a two-way version of transclusion:
instead of the source material being inherited by the derivative
article, under identification, the source is shared between several
articles.  Thus, changes in one place will be mirror in each of the
other places.  This is developed in Section [[id:identification]].


*** Clusions                                                       :noexport:
:PROPERTIES:
:LATEX_LABEL: clusions
:ID: clusions
:END:

We refer to specific instructions specifying an inclusion,
transclusion, or identification as a \emph{clusion}.  (By analogy to
the morphisms of category theory.)  In this lingo, we could also refer
to identification as \emph{biclusion}.

Both identification and transclusion are represented as links inside
the \inp{text} field of an article, and this property is definitional
for clusions.  

Identification, on the other hand, is currently implemented as a live,
one-time operation, and so it isn't strictly an example.  However,
once we have a proper versioning system working, it would be fairly
easy to do inclusion as a proper clusion like the others (by making it
point at a specific version of a document from which to draw text) --
assuming that is what is desired.  It may be that the user wants to
simply quote from the other document, and doesn't want to do clusion
maintenance.  We'll have to give some thought to what way of operating
is most desirable here.

I haven't thought of any other major classes of clusions (at least,
not yet), but just to point out that any clusion can be composed with
straightforward text operations (e.g. reversing the characters in a
cluded region) to obtain another clusion.

Mainatining clusions is part of a broader problem of maintaining
consistency conditions, see Section [[id:consistency]].


*** Allowable sources                                              :noexport:
:PROPERTIES:
:LATEX_LABEL: allowable-sources
:ID: allowable-sources
:END:

Compare Note [[id:types-of-text]], which talks about the different
allowable kinds of \inp{text}, but note that, one should be able to
clude things other than text.  The set of objects that can be cluded
is same as the set of objects that a scholium can be \inp{about},
i.e., anything a link can point at.


*** Derivatives and versioning                                     :noexport:

In order to get the relevant functions for building derivatives set up
properly, we really should have version management in place.


*** List processing as a prototypical example                      :noexport:
:PROPERTIES:
:LATEX_LABEL: including-transcluding-and-lisp
:ID: including-transcluding-and-lisp
:END:

The ``\kw{,@}'' from LISP comes to mind when thinking about
transcluding, whereas shared list structure is like identification.
It would be interesting to spell the relationship out in detail.

One further thought on the subject is that we may sometimes want to
transclude symbols and s-exps of LISP code -- which brings the
discussion full circle pretty quickly.


*** Boundaryless formulations                                      :noexport:
:PROPERTIES:
:LATEX_LABEL: boundaryless-formulations
:ID: boundaryless-formulations
:END:

The simplest cases to deal with appear to be those in which no
boundary is mentioned.  For example, cluding the whole of some article
$A$ into another article $B$.  In practice, sometimes we can stick to
a boundaryless treatment; other times, boundaries are unavoidable.


*** Clusion algorithms                                             :noexport:

It would probably be good to put an overview of things like
[[id:the-transclusion-algorithm]] here, so that the subsequent
discussion of markup makes sense.  (We could talk about the easy
work-around for building this document, and contrast it with the more
intensive operations that go on in the *Compilation* buffer (cf. Note
[[id:making-a-compilation]]).


*** Splitting text properties                                      :noexport:
:PROPERTIES:
:LATEX_LABEL: splitting-text-properties
:ID: splitting-text-properties
:END:

Text inserted in the middle of a quotation does not derive from the
same source as the quoted text.  Therefore, it typically should not
take on the `derives-from' markup of the surrounding text.  For a
discussion of inserting within a marked up region in general (i.e.,
not just in the cases having to do with derivatives), see Note
[[id:inserting-text-in-middle-of-marked-up-region]].


*** Splitting clusions                                             :noexport:

Notice that edits in either the source or the recipient 
article can cause a clusion to split, as illustrated in
Figure
# [[id:Two-ways-to-cause-clusions-to-split]].

\begin{figure}
\begin{center}
\begin{tabular}{c}
\begin{tabular}{ccc}
     $A$      &$\rightarrow$&         $B$   \\
\verb|xxabcd| &             &  \verb|yyabcd| \\
\verb|efgxxx| &             &  \verb|efgyyy| \\
\end{tabular} \\
\ \\

\hline \\

\begin{tabular}{ccc}
     $A'$     &$\rightarrow(\times 2)$&        $B'$   \\
\verb|xxabcd| &                       &  \verb|yyabcd| \\
\verb|xxxefg| &                       &  \verb|efgyyy| \\
\end{tabular} \\

\emph{or} \\
\ \\
\begin{tabular}{ccc}
     $A'$     &$\rightarrow(\times 2)$&        $B'$   \\
\verb|xxabcd| &                       &  \verb|yyabcd| \\
\verb|efgxxx| &                       &  \verb|yyyefg| \\
\end{tabular}
\end{tabular}
\end{center}
\caption{Edits in either $A$ or $B$ can cause a clusion to split
\label{Two-ways-to-cause-clusions-to-split}}
\end{figure}


*** Masking clusions                                               :noexport:
:PROPERTIES:
:LATEX_LABEL: masking-clusions
:ID: masking-clusions
:END:

We want to mask clusions in much the same way we mask links (Note
[[id:masking-links]]).  Indeed, clusions \emph{are} essentially links,
by definition (Note [[id:clusions]]).


*** Format of text with derivatives
:PROPERTIES:
:LATEX_LABEL: format-of-text-with-derivatives
:ID: format-of-text-with-derivatives
:END:

The format of the \inp{text} field for articles with derivatives is as
follows:
#+BEGIN_SRC elisp :tangle no
(twd <string | clusion> ...)
#+END_SRC
Each clusion is a link with the corresponding instruction consed
onto the front of it (cf. Note [[id:links]]).  The three instructions
are `transclude', `identify', and `include'.

For example,
#+BEGIN_SRC elisp :tangle no
(twd "This Note can be used as part of an example.\n" 
     (transclude "Format of text with derivatives"))
#+END_SRC
or,
#+BEGIN_SRC elisp :tangle no
(twd "Part of this Note can be used as part of an example.\n" 
     (transclude "Format of text with derivatives" 
                 (passage 1 25)))
#+END_SRC

There is a small break in transparency here; presumably this won't be
a problem (Note [[id:principle-of-transparency]]).


*** Transclusion and freedom                                       :noexport:
:PROPERTIES:
:LATEX_LABEL: transclusion-and-freedom
:ID: transclusion-and-freedom
:END:

The right to make and circulate \emph{derivative works} is important
(i.e., when it is allowed!).  One easy sort of derivative is a
compilation of all of the sub-objects that have a given property.  For
example, one could put together a collection of all the first
paragraphs drawn from the various sections of an article, or all the
paragraphs that have been marked as ``needs revision'', or
``theoretically interesting'', etc.  Transclusion makes it easy to
build simple, useful, derivatives of this sort, and keep them up to
date as the master document changes.  (Sometimes one would want to use
somewhat special instructions, e.g. in order to collect only the
\emph{new} items matching an otherwise-global search criterion.)


*** The dependence of the various derivatives on `commit-edits'    :noexport:
:PROPERTIES:
:LATEX_LABEL: derivatives-and-committing
:ID: derivatives-and-committing
:END:

I think we may have to do a commit after running `transclude-article',
since it involves changing the \inp{text} field.  By contrast, running
`include-article' causes new scholia to be stored automatically, but
we left committing the text field to the user.  So, I'm not sure; if
there is a way to do transclusion without requiring a commit
automatically, that might be kind of nice.

Note also that each of the different derivative styles will have
things to look for whenever they commit \emph{again}.  (E.g. articles
with inclusions should be inspected to see if perhaps all of the
included text has been deleted.)


*** Derivatives outside of the scholium system                     :noexport:

We leave it up to the user to write a suitable function for quoting
text from scholium system objects to non-scholium system objects (if
the user has any of these!).


*** Technical difficulties with text properties                    :noexport:
:PROPERTIES:
:LATEX_LABEL: difficulties-with-text-properties
:ID: difficulties-with-text-properties
:END:

The fundamental difficulty with text properties seems to be that using
them comes at a non-trivial cost.  So we don't use them for everything
(cf. Note [[id:alternative-to-identification]]).

When doing transclusion, rather than using a uniform text property, we
need a text property that gives a unique ID to each character within
the marked up region (Figure
# [[id:Rearrangement-not-detected-using-uniform-text-properties]],
Note [[id:transclusion-markup-design]]).

I've been assuming that \emph{typical} text properties designating the
association of a region with a scholium will be ``sticky'' -- if
someone adds to a marked-up region, the added text will bear the new
markup.  At some point, we might have a non-sticky option.  However,
the text properties associated with transclusions should always be
non-sticky, since text added in the middle of a quoted passage needs
to be treated as an ``island'' in the middle of the transclusion
(which actually gets split in two).

The problem arises in the fact that Emacs makes it hard and/or ugly to
use an individual text property for each transclusion (see Note
[[id:many-scholium-properties]]).  The relevant experiment took place
in CVS versions 41 through 43; version 44 was then identical to
version 41.

The point is, that I've been maintaining all of the data about scholia
on precisely one text property, which of course takes on different
values as needed.  However, the ``stickiness'' of each text property
is controlled individually, and I can't continue to use this trick.

I could, I suppose, use one sticky and one non-sticky text property,
but I think that there may be a better approach involving some work on
the text property system itself.  This will need some more
investigation.


*** Treating clusions                                              :noexport:
:PROPERTIES:
:LATEX_LABEL: treating-clusions
:ID: treating-clusions
:END:

The following subsections provide commands for \emph{building clusions
  interactively}, and for \emph{rendering them properly}.

