** Inclusion
:PROPERTIES:
:LATEX_LABEL: inclusion
:ID: inclusion
:END:

*** On `include-article'
:PROPERTIES:
:LATEX_LABEL: include-article
:ID: include-article
:END:

It is simple enough to find an article and insert its text at point
(compare `insert-buffer').

%% We then need to add `derives-from' and `derives-to' properties (note
%% similarity to backlinking; indeed, we reuse `put-backlinks', relying
%% on the general way in which it was written; see Note
%% [[id:put-backlinks]]).


#+BEGIN_SRC elisp
(defun include-article (article)
  (interactive (list (read-article-name)))
  (let ((beg (point)))
    (insert (sch-plain-text (get-article article)))
    ;; this condition isn't really strong enough
    (when name-of-current-article
      (scholium
       `(derives-from ,name-of-current-article ,article ,(genref))
       nil
       `((passage (,name-of-current-article
                   ,beg
                   ,(point))))
       'derives-from
       'system))))
#+END_SRC

*** By default, don't print `derives-from' scholia

Typically we don't need to see `derives-from' scholia, although it
could be handy to write a special display mode in which these scholia
are printed (and probably special semantics for how they are
displayed).


#+BEGIN_SRC elisp
(add-to-list 'non-printing-types 'derives-from)
#+END_SRC

*** Deleting `derives-from' properties                             :noexport:

If upon reparsing, if no sections are actually marked up with a
`derives-from' property that was previously recorded, it can be
assumed that the text that was quoted from that particular source
article has been deleted.  In which case, odds are that the
formerly-derivative document doesn't derive from that source any
longer.


*** Add `include-article-formatting-minimally'                     :noexport:

It might be helpful to have a function that would do everything
that the previous version does, but without marking the text up,
or perhaps just running it through `format'.  But I'm going
to hold off on this until the use cases seem clearer to me.


*** Record version number of included article                      :noexport:

Since inclusions are static, we should probably make note of the
specific version of the source article that the recipient derives
from.


*** Including passages                                             :noexport:

It might be useful to support optional ``beg'' and ``end'' arguments
that would make it possible to quote only a substring of the
\inp{article} that is being included.  This seems most likely to be
useful in a setting in which we select the passage to include
interactively.  (Cf. Note [[id:simple-selection-for-transclusion]].)

