** Further notes on derivative works                               :noexport:

*** Derivatives and copyright

Recall that for copyright purpose, it is \emph{expression} that is
supposed to be examined when deciding whether a given work derives
from some other work.  This somewhat elusive quality is going to be
harder to capture than the property of being a derivative via direct
quotation and subsequent revision.


*** Pedigrees
:PROPERTIES:
:LATEX_LABEL: pedigrees
:ID: pedigrees
:END:

When adding metadata to show what articles a given article derives
from, we probably only want to bother with the parent, not with
ancestors from earlier generations.  More extensive information about
an article's pedigree can be found by chasing backlinks, as needed.


*** Aggressive management of derivatives
:PROPERTIES:
:LATEX_LABEL: aggressive-dop
:ID: aggressive-dop
:END:

A more ``aggressive'' solution to recording information about
derivative works would be to mark up rendered articles with a text
property that identifies them; this way, whenever the text is
cut-and-pasted to a new buffer, the text property will be carried
along, and the source of the text can be identified and noted
when the recipient article is reparsed and committed.


*** Fancy derivatives
:PROPERTIES:
:LATEX_LABEL: fancy-derivatives
:ID: fancy-derivatives
:END:

It may be useful at times to carry over certain scholia attached to
the region that is being quoted.  There are probably a number of
variations that people would be interested in trying.


*** Eventual improved support for virtual collections?
:PROPERTIES:
:LATEX_LABEL: improved-support-for-virtual-collections
:ID: improved-support-for-virtual-collections
:END:

In Note [[id:derivative-works-in-the-scholium-system]] we briefly
contrasted derivative articles with collections and indices.  It seems
likely that we can come up with tools that will make it easier to
build useful indices; subcollections (Section [[id:subcollections]])
seem to capture the basic idea, but there is room to grow there.


*** Derivative articles and forking
:PROPERTIES:
:LATEX_LABEL: derivative-articles-and-forking
:ID: derivative-articles-and-forking
:END:

One obvious way to fork an article is simple -- to include it in full
and then begin edits there.  The ability to do this gives users quite
a bit of freedom; however, it is worth noting that it can frequently
be to a user's benefit to get their changes inserted in (or around)
the original source, instead of placing them in a separate derivative
version.  (This relates to Section [[id:philosophy]].)


*** Tracking changes in parents

Transcluding will make it so that changes to the parent are
immediately reflected in the child.  This is not so with inclusions;
however, owners of articles that use inclusion may still want to be
\emph{updated} when the parent changes.  See Section [[id:bidi]].


*** Tracking changes in children

Nevertheless, there are certainly times when it is beneficial or
expedient to create a modified version.  To cater to users in this
situation, we could also set up a derivative-tracking device, who's
function would be to update the original author about the fate and
progress of any derived versions.  See Section [[id:bidi]].


*** Overviews
:PROPERTIES:
:LATEX_LABEL: overviews
:ID: overviews
:END:

It would be nice to include markup associating an overview with the
section of the document that was being overviewed.

\emph{Editing (or mixing) down} is essentially similar thing done in a
different spirit.  Whereas I'm imagining that the edited-down version
would replace the old version, the overview would likely exist in
parallel with the original.


*** Transclusion with modifications

In addition to the overviews of Note [[id:overviews]], we could be
interested in other sorts of ``transclusion with modifications''.  For
example, if the overview is created by transcluding only the first
paragraph from every chapter, other modified versions could be created
by replacing \emph{foo} by \emph{bar} everywhere.


*** Transclusion (typically) induces a linear structure
:PROPERTIES:
:LATEX_LABEL: transclusion-induces-linear-structure
:ID: transclusion-induces-linear-structure
:END:

If an article is built out of other transcluded articles, then it
should be possible to abstract an \emph{order}, so that one can say
``next article'' or ``previous article'' and have these things make
sense.  But of course, this order can easily be broken, say by
allowing there to be two ``next articles'' (compare \emph{Literary
  Machines}).  Also note that nested transclusions (typically) induce
a tree structure.


*** Transclusion-like actionable derivatives

In order to keep the first example of a scholium given in section
# [[id:examples]],
``Remark on Scholium Definition'', up to date, it
would be nice not to have to keep changing the numbers that identify
the the beginning and end of the region being indicated by hand.  This
problem could be solved by putting a scholium in place of each number
that renders as the appropriate number whenever the article is
rendered.  A standard scholium \inp{about} the region in question
would be maintained by reparsing (Section [[id:parsing]]), but the
actual numbers that designate the beginning and end of this region
will move around.  Designing the actionable scholium that would
accomplish the job here will take a bit of doing.


*** Indivisible read-only text for collapsed labels

Perhaps collapsed text (Note [[id:transcluding-and-outlines]]) should
have a special read-only property (alternatively, changes to such text
would constitute suggested changes to the \inp{name} of the article
that was transcluded; see Note [[id:identification-use-case]]).


*** Scholia Display as transclusion

Although it isn't technically put together that way (at least, not
now), one could think of the Scholia Display as being an article that
is put together by transcluding all of the scholia attached to the
current main article.


*** Rendering deleted objects
:PROPERTIES:
:LATEX_LABEL: rendering-deleted-objects
:ID: rendering-deleted-objects
:END:

This is a general problem that affects both rendering straightforward
articles which happen to be transcluded and rendering articles with
transclusions that point at articles that have been deleted.
Presumably, some kind of ``404 File not found'' error will be
displayed at an appropriate point in the text.


*** Building transcluded articles by reparsing

Particularly if transcluded portions of a document are not directly
editable, it might make sense to build ``text with transclusions'' by
first assembling the content of a buffer containing transclusions, and
then parsing the text properties.  If the transcluded portions were
directly editable, we could get into a somewhat tricky situation
(e.g. should shearing three characters off of the end of the image of
some transcluded text also change the transclusion command so that
those characters are not copied over in the future? -- probably,
although there are probably better ways of editing transclusion
specifics).

This is essentially what I've decided to do; see Note Transclusion
from a design perspective.


*** Rendering text with derivative pieces to specific places

Right now, text that includes transclusions is set up to only render
to the ``Main Article Display'' buffer (because the \inp{text} field
is not a buffer).  We could set things up so that articles whose text
contains transclusions could be associated with specific buffers where
the rendered text would appear.  This would require some changes to
`scholia-overwhelm-display' (see Note
[[id:scholia-overwhelm-display]]).

