(add-to-list 'load-path (expand-file-name "dev" "."))
(load "/home/joe/code/futon3/contrib/flexiarg.el")
(provide 'flexiarg)
(require 'arxana-patterns)
(with-temp-buffer
  (arxana-flexiarg-collection-mode)
  (arxana-flexiarg--prepare-buffer '("/home/joe/code/futon4/docs/testing.flexiarg"))
  (arxana-flexiarg-show-conclusions)
  (let ((meta (car arxana-flexiarg--metadata-overlays))
        (ctx (car arxana-flexiarg--context-overlays)))
    (message "metadata-display:%S" (overlay-get meta 'display))
    (message "context-display:%S" (overlay-get ctx 'display))))
