(add-to-list 'load-path "/home/joe/code/futon4/dev")
(load "/home/joe/code/futon3/contrib/flexiarg.el")
(provide 'flexiarg)
(require 'arxana-patterns)
(require 'seq)

(with-temp-buffer
  (arxana-flexiarg-collection-mode)
  (arxana-flexiarg--prepare-buffer '("/home/joe/code/futon4/docs/testing.flexiarg"))
  (message "state:%s" arxana-flexiarg--cycle-state)
  (arxana-flexiarg-cycle-buffer)
  (message "after1:%s" arxana-flexiarg--cycle-state)
  (let* ((meta (or (seq-find (lambda (ov)
                               (let ((disp (overlay-get ov 'before-string)))
                                 (and disp (> (length disp) 0))))
                             arxana-flexiarg--metadata-overlays)
                   (car arxana-flexiarg--metadata-overlays)))
         (ctx (car arxana-flexiarg--context-overlays)))
    (princ (format "metadata-placeholder:%S\n" (overlay-get meta 'before-string)))
    (princ (format "metadata-intangible:%S\n" (overlay-get meta 'intangible)))
    (princ (format "metadata-invisible-prop:%S\n"
                   (get-text-property (overlay-start meta) 'invisible)))
    (princ (format "context-placeholder:%S\n" (or (overlay-get ctx 'before-string)
                                                  (overlay-get ctx 'display))))
    (princ (format "context-intangible:%S\n" (overlay-get ctx 'intangible)))
    (princ (format "context-invisible-prop:%S\n"
                   (get-text-property (overlay-start ctx) 'invisible))))
  (princ (format "stage1:%S\n" (mapcar (lambda (s)
                                         (save-excursion
                                           (goto-char (point-min))
                                           (search-forward s)
                                           (outline-invisible-p (line-beginning-position))))
                                       '("@arg" "! conclusion" "+ CONTEXT:" "Set expectations"))))
  (arxana-flexiarg-cycle-buffer)
  (message "after2:%s" arxana-flexiarg--cycle-state)
  (princ (format "stage2:%S\n" (mapcar (lambda (s)
                                         (save-excursion
                                           (goto-char (point-min))
                                           (search-forward s)
                                           (outline-invisible-p (line-beginning-position))))
                                       '("@arg" "! conclusion" "+ CONTEXT:" "Set expectations"))))
  (arxana-flexiarg-cycle-buffer)
  (message "after3:%s" arxana-flexiarg--cycle-state)
  (princ (format "stage3:%S\n" (mapcar (lambda (s)
                                         (save-excursion
                                           (goto-char (point-min))
                                           (search-forward s)
                                           (outline-invisible-p (line-beginning-position))))
                                       '("@arg" "! conclusion" "+ CONTEXT:" "Set expectations")))) )
